import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

const mobileRoot = join(dirname(fileURLToPath(import.meta.url)), '../..');
const apiSource = readFileSync(join(mobileRoot, 'lib/api.ts'), 'utf8');
const mapSource = readFileSync(join(mobileRoot, 'app/(tabs)/map.tsx'), 'utf8');
const briefSource = readFileSync(join(mobileRoot, 'components/map/CampgroundBriefSection.tsx'), 'utf8');

test('the factual campground brief has a free source-owned API separate from personalized planning', () => {
  assert.match(apiSource, /getCampgroundBrief: \(id: string\) =>/);
  assert.match(apiSource, /\/api\/campsites\/\$\{encodeURIComponent\(facilityId\)\}\/brief/);
  assert.match(apiSource, /getCampsiteInsight: \(data: CampsiteInsightRequest\) =>/);
  assert.match(apiSource, /\/api\/ai\/campsite-insight/);
});

test('Recreation.gov campsite cards resolve their parent campground brief', () => {
  assert.match(apiSource, /raw\.startsWith\('ridb_site:'\) \? raw\.split\(':'\) : \[\]/);
  assert.match(apiSource, /const facilityId = siteParts\[1\] \|\| ridbFacilityIdFromCanonicalCampId\(raw\) \|\| raw/);
});

test('camp detail starts a stable factual brief request without automatically charging for synthesis', () => {
  assert.match(mapSource, /const briefPromise = detailFetchId/);
  assert.match(mapSource, /api\.getCampgroundBrief\(detailFetchId\)/);
  assert.match(mapSource, /await loadCampDetailForCamp\(selectedCamp, \{ loadInsight: false \}\)/);
  assert.match(mapSource, /onPersonalize=\{\(\) => selectedCamp && openCampInsight\(selectedCamp, campDetail\)\}/);
});

test('late brief responses are bound to the selected campground identity', () => {
  assert.match(mapSource, /const requestIsCurrent = \(\) => placeSheetRequestIsCurrent\(sheetRequest\) && selectedCampRef\.current\?\.id === camp\.id/);
  assert.match(mapSource, /if \(!requestIsCurrent\(\)\) return;\s+if \(result\.status === 'ready'\) setCampgroundBrief\(result\.value\)/);
  assert.match(mapSource, /campgroundBriefOwnerRef\.current === selectedCamp\?\.id/);
});

test('the brief renders facts, weather, sources, unavailable fields, and nearby services without an AI label', () => {
  for (const label of [
    'Campground brief',
    'Access and setup',
    'Weather',
    'Mobile coverage',
    'Booking and contact',
    'Useful nearby',
    'Places nearby',
    'Sources',
    'Not listed:',
    'Personalize this stay',
  ]) {
    assert.ok(briefSource.includes(label), `missing brief label: ${label}`);
  }
  assert.doesNotMatch(briefSource, />\s*AI\s*</i);
  assert.doesNotMatch(briefSource, /generated by ai/i);
});

test('existing campground modules remain alongside the new brief', () => {
  for (const contract of [
    /campDetail\.campsites/,
    /campDetail\.site_types/,
    /campDetail\.amenities/,
    /campMobileCoverage/,
    /CampCommentsSection/,
    /FirstPartyRatingSection/,
    /CampFieldReportsSection/,
    /openCampEdit\('suggest'\)/,
    /campSourceUrl/,
  ]) {
    assert.match(mapSource, contract);
  }
});
