from __future__ import annotations

import asyncio
import json
import os
import tempfile
import unittest
from unittest.mock import AsyncMock, Mock, patch

from ai import planner
from config.settings import settings
from dashboard import server
from dashboard.campground_briefs import build_campground_brief_v3
from dashboard.campground_planning_briefs import (
    build_campground_planning_brief,
    cached_campground_planning_brief,
    campground_planning_evidence,
)
from db import store


def _detail() -> dict:
    return {
        "id": "234059",
        "name": "Juniper Campground",
        "lat": 38.57,
        "lng": -109.55,
        "land_type": "National Park",
        "verified_source": "National Park Service",
        "official_url": "https://www.nps.gov/example/campground.htm",
        "last_checked": 1_780_000_000,
        "site_types": ["Tent", "RV"],
        "amenities": ["Water", "Picnic tables"],
        "campsites_count": 42,
        "reservable": True,
    }


def _model_result() -> dict:
    official = "https://www.nps.gov/example/campground.htm"
    return {
        "summary": {"text": "Plan around the signed seasonal operating window.", "source_urls": [official]},
        "best_time": {"text": "The official page lists a spring through fall operating window.", "source_urls": [official]},
        "access_and_rig": {"text": "Review the posted vehicle limits before bringing a longer rig.", "source_urls": [official]},
        "service_and_signal": {"text": "", "source_urls": []},
        "look_out_for": [{"text": "Seasonal dates can change with conditions.", "source_urls": [official]}],
        "preparation": [{"text": "Save the official contact before leaving service.", "source_urls": [official]}],
        "nearby_context": [],
    }


class CampgroundPlanningBriefValidationTests(unittest.TestCase):
    def setUp(self):
        factual = build_campground_brief_v3(_detail(), generated_at=1_780_000_100)
        self.evidence = campground_planning_evidence(factual)

    def test_accepts_only_cited_sections_and_hides_provider_metadata(self):
        generated = _model_result()
        generated["nearby_context"] = [
            {"text": "A guessed nearby fuel stop is always open.", "source_urls": ["https://invalid.example/fuel"]},
        ]
        brief = build_campground_planning_brief(
            generated,
            self.evidence,
            [{"title": "Official campground", "url": "https://www.nps.gov/example/campground.htm"}],
            now=1_780_000_200,
        )

        self.assertEqual(brief["schema_version"], "campground-planning-brief-v1")
        self.assertEqual(brief["nearby_context"], [])
        self.assertEqual(len(brief["sources"]), 1)
        self.assertNotIn("provider", brief)
        self.assertNotIn("model", brief)
        self.assertNotIn("generated by ai", str(brief).casefold())

    def test_cache_is_bound_to_source_revision_and_expiry(self):
        brief = build_campground_planning_brief(
            _model_result(),
            self.evidence,
            [],
            now=1_780_000_200,
        )
        self.assertIsNotNone(cached_campground_planning_brief(brief, self.evidence, now=1_780_000_201))
        self.assertIsNone(cached_campground_planning_brief(brief, self.evidence, now=brief["expires_at"]))
        changed = {**self.evidence, "site_types": ["Tent"]}
        self.assertIsNone(cached_campground_planning_brief(brief, changed, now=1_780_000_201))


class CampgroundPlanningBriefOpenAITests(unittest.TestCase):
    def test_responses_request_uses_web_search_structured_output_and_no_storage(self):
        response = Mock()
        response.status_code = 200
        response.json.return_value = {
            "output": [
                {
                    "type": "web_search_call",
                    "action": {
                        "sources": [{
                            "title": "Official campground",
                            "url": "https://www.nps.gov/example/campground.htm",
                        }],
                    },
                },
                {
                    "type": "message",
                    "content": [{"type": "output_text", "text": __import__("json").dumps(_model_result())}],
                },
            ],
        }
        evidence = campground_planning_evidence(
            build_campground_brief_v3(_detail(), generated_at=1_780_000_100)
        )
        with (
            patch.object(planner.settings, "openai_api_key", "test-key"),
            patch.object(
                planner.settings,
                "openai_campground_brief_model",
                "gpt-5.4-nano",
            ),
            patch.object(planner.httpx, "post", return_value=response) as post,
        ):
            result = planner.generate_campground_planning_brief(
                evidence,
                safety_identifier="safe-test-id",
                max_attempts=1,
            )

        payload = post.call_args.kwargs["json"]
        self.assertEqual(post.call_args.args[0], "https://api.openai.com/v1/responses")
        self.assertEqual(payload["model"], "gpt-5.4-nano")
        self.assertFalse(payload["store"])
        self.assertEqual(payload["tools"][0]["type"], "web_search")
        self.assertEqual(payload["tools"][0]["search_context_size"], "low")
        self.assertEqual(payload["reasoning"], {"effort": "none"})
        self.assertEqual(payload["max_output_tokens"], 2200)
        self.assertEqual(payload["text"]["format"]["type"], "json_schema")
        self.assertTrue(payload["text"]["format"]["strict"])
        self.assertEqual(payload["safety_identifier"], "safe-test-id")
        self.assertEqual(result["sources"][0]["url"], "https://www.nps.gov/example/campground.htm")


class CampgroundPlanningBriefUnlockTests(unittest.TestCase):
    def setUp(self):
        self.original_db_path = settings.db_path
        tmp = tempfile.NamedTemporaryFile(delete=False)
        tmp.close()
        self.db_path = tmp.name
        settings.db_path = self.db_path
        store.init_db()
        self.user_id = store.create_user(
            "brief@example.com",
            "brief_user",
            "hash",
            "brief-code",
        )
        store.add_credits(self.user_id, 10, "Test balance")

    def tearDown(self):
        settings.db_path = self.original_db_path
        try:
            os.unlink(self.db_path)
        except OSError:
            pass

    def test_unlock_is_permanent_and_charges_exactly_once(self):
        first = store.unlock_camp_planning_brief(
            self.user_id, "234059", 5, "Campground brief - Juniper"
        )
        second = store.unlock_camp_planning_brief(
            self.user_id, "234059", 5, "Campground brief - Juniper"
        )
        user = store.get_user_by_id(self.user_id)

        self.assertTrue(first["newly_unlocked"])
        self.assertEqual(first["credits_spent"], 5)
        self.assertFalse(second["newly_unlocked"])
        self.assertEqual(second["credits_spent"], 0)
        self.assertEqual(user["credits"], 5)

    def test_failed_generation_refund_removes_new_unlock(self):
        store.unlock_camp_planning_brief(
            self.user_id, "234059", 5, "Campground brief - Juniper"
        )
        self.assertTrue(store.refund_camp_planning_brief_unlock(
            self.user_id, "234059", "Refund - unavailable"
        ))
        self.assertIsNone(store.get_camp_planning_brief_unlock(self.user_id, "234059"))
        self.assertEqual(store.get_user_by_id(self.user_id)["credits"], 10)

    def test_job_state_is_durable_and_bound_to_user_camp_and_revision(self):
        evidence = {"entity": {"id": "234059", "name": "Juniper"}}
        created = store.create_camp_planning_brief_job(
            "job-1",
            self.user_id,
            "234059",
            "revision-1",
            evidence,
            refund_on_error=True,
        )
        self.assertEqual(created["status"], "queued")
        self.assertEqual(
            store.find_active_camp_planning_brief_job(
                self.user_id, "234059", "revision-1"
            )["id"],
            "job-1",
        )
        store.update_camp_planning_brief_job("job-1", "running")
        self.assertEqual(
            store.get_camp_planning_brief_job("job-1", self.user_id)["evidence"],
            evidence,
        )
        store.update_camp_planning_brief_job("job-1", "ready")
        self.assertIsNone(store.find_active_camp_planning_brief_job(
            self.user_id, "234059", "revision-1"
        ))


class CampgroundPlanningBriefEndpointTests(unittest.TestCase):
    def test_endpoint_charges_five_once_and_returns_background_job(self):
        user = {"id": 7, "credits": 10, "plan_type": "free", "is_admin": 0}
        with (
            patch.object(server.settings, "openai_api_key", "test-key"),
            patch.object(server, "_load_campsite_detail", new=AsyncMock(return_value=_detail())),
            patch.object(server, "get_service_places", new=AsyncMock(return_value=[])),
            patch.object(server, "has_active_plan", return_value=False),
            patch.object(server, "get_camp_planning_brief_unlock", return_value=None),
            patch.object(server, "unlock_camp_planning_brief", return_value={
                "unlocked": True,
                "newly_unlocked": True,
                "credits_spent": 5,
                "credit_balance": 5,
            }) as unlock,
            patch.object(server, "get_camp_brief", return_value=None),
            patch.object(server, "find_active_camp_planning_brief_job", return_value=None),
            patch.object(server, "create_camp_planning_brief_job", return_value={
                "id": "job-1",
                "facility_id": "234059",
                "status": "queued",
            }),
            patch.object(server, "_schedule_camp_planning_brief_job") as schedule,
        ):
            result = asyncio.run(server.campground_planning_brief_v1("234059", user))

        body = json.loads(result.body)
        self.assertEqual(result.status_code, 202)
        self.assertEqual(body["access"]["credits_spent"], 5)
        self.assertEqual(body["access"]["new_balance"], 5)
        self.assertEqual(body["status"], "preparing")
        unlock.assert_called_once()
        self.assertEqual(unlock.call_args.args[2], 5)
        schedule.assert_called_once_with("job-1")

    def test_background_job_refunds_a_new_unlock_when_research_fails(self):
        job = {
            "id": "job-1",
            "user_id": 7,
            "facility_id": "234059",
            "evidence": campground_planning_evidence(
                build_campground_brief_v3(_detail(), generated_at=1_780_000_100)
            ),
            "refund_on_error": 1,
        }
        with (
            patch.object(server, "get_camp_planning_brief_job", return_value=job),
            patch.object(server, "update_camp_planning_brief_job") as update,
            patch.object(server, "refund_camp_planning_brief_unlock", return_value=True) as refund,
            patch("ai.planner.generate_campground_planning_brief", side_effect=RuntimeError("no response")),
        ):
            asyncio.run(server._execute_camp_planning_brief_job("job-1"))

        refund.assert_called_once()
        self.assertEqual(update.call_args_list[-1].args[:2], ("job-1", "error"))


if __name__ == "__main__":
    unittest.main()
