from __future__ import annotations

import asyncio
import json
from unittest.mock import AsyncMock, patch

from dashboard import server
from dashboard.campground_briefs import build_campground_brief_v3


def _recreation_detail(**overrides):
    detail = {
        "id": "234059",
        "name": "Juniper Campground",
        "lat": 38.57,
        "lng": -109.55,
        "land_type": "National Park",
        "verified_source": "Recreation.gov",
        "official_url": "https://www.recreation.gov/camping/campgrounds/234059",
        "booking_url": "https://www.recreation.gov/camping/campgrounds/234059",
        "last_checked": 1_780_000_000,
        "source_freshness": "Checked from Recreation.gov.",
        "site_types": ["Tent", "RV"],
        "amenities": ["Water", "Picnic tables", "Hookups"],
        "activities": ["Camping"],
        "campsites_count": 42,
        "campsites": [
            {
                "id": "1",
                "equipment_length": "35 ft",
                "driveway": "Back-in",
                "surface": "Gravel",
                "hookups": True,
                "accessible": True,
            },
        ],
        "reservable": True,
        "price_summary": {"label": "$20-$40 per night"},
        "reservation_notes": "Reserve on Recreation.gov when available.",
        "phone": "555-0100",
        "mobile_coverage": {
            "records": [{
                "provider": "Example Mobile",
                "technology": "4G LTE",
                "availability_class": "modeled_available",
                "data_date": "2026-06",
            }],
            "source_label": "FCC modeled",
            "last_checked": 1_780_000_000,
        },
        "trip_services": [{
            "id": "fuel-1",
            "name": "Moab Fuel",
            "type": "fuel",
            "lat": 38.58,
            "lng": -109.54,
            "source": "osm",
        }],
        "things_to_see": [{
            "id": "view-1",
            "name": "Canyon View",
            "type": "viewpoint",
            "lat": 38.59,
            "lng": -109.53,
            "source": "nps",
        }],
    }
    detail.update(overrides)
    return detail


def _fact_values(brief):
    return {item["id"]: item["value"] for item in brief["facts"]}


def test_developed_recreation_brief_is_free_factual_and_complete():
    brief = build_campground_brief_v3(_recreation_detail(), generated_at=1_780_000_100)

    assert brief["schema_version"] == "campground-brief-v3"
    assert brief["evidence_status"] == "complete"
    assert _fact_values(brief)["site_count"] == "42"
    assert _fact_values(brief)["reservability"] == "Available for listed inventory"
    assert brief["site_types"] == ["RV", "Tent"]
    assert any(item["id"] == "max_rig_length" and "35 ft" in item["value"] for item in brief["access"])
    assert any(item["id"] == "road_surface" and item["value"] == "Gravel" for item in brief["access"])
    assert any(item["name"] == "Moab Fuel" and item["label"] == "Fuel" for item in brief["nearby_services"])
    assert brief["mobile_coverage"]["records"][0]["availability"] == "Modeled coverage"
    assert brief["personalized_planning"]["access"] == "explorer_or_credits"
    assert "generated by ai" not in json.dumps(brief).casefold()


def test_dispersed_brief_uses_only_listed_access_and_stay_facts():
    brief = build_campground_brief_v3({
        "id": "thp_dispersed_1",
        "name": "Juniper Wash",
        "land_type": "Dispersed",
        "source": "trailhead",
        "last_checked": 1_780_000_000,
        "site_types": ["Tent"],
        "amenities": [],
        "campsites_count": 0,
        "reservable": False,
        "access_notes": "Use the signed gravel access road.",
        "stay_limit": "14 days",
    }, generated_at=1_780_000_100)

    values = json.dumps(brief)
    assert _fact_values(brief)["camp_type"] == "Dispersed"
    assert any(item["id"] == "access_notes" for item in brief["access"])
    assert any(item["id"] == "stay_limit" for item in brief["booking_contact"])
    assert "safe" not in values.casefold()
    assert "suitable" not in values.casefold()
    assert "available for listed inventory" not in values.casefold()


def test_nps_brief_preserves_official_source_and_operational_note():
    detail = _recreation_detail(
        id="nps:yose:upper-pines",
        name="Upper Pines Campground",
        verified_source="National Park Service",
        official_url="https://www.nps.gov/yose/planyourvisit/upperpines.htm",
        operating_season="Open year-round by reservation.",
        provider_notices=[{
            "label": "Operating note",
            "text": "Seasonal reservation windows vary.",
        }],
    )
    brief = build_campground_brief_v3(detail, generated_at=1_780_000_100)

    assert brief["sources"][0]["label"] == "National Park Service"
    assert _fact_values(brief)["operating_season"] == "Open year-round by reservation."
    assert brief["conditions"][0]["value"] == "Seasonal reservation windows vary."


def test_rv_private_brief_keeps_rig_hookup_and_contact_evidence():
    detail = _recreation_detail(
        id="private-rv-1",
        name="Portal RV Stay",
        land_type="Private RV park",
        verified_source="Trailhead",
        max_rig_length="45 ft",
        amenities=["Full hookups", "Laundry"],
        campsites=[{"id": "rv-1", "surface": "Paved", "hookups": True}],
        phone="555-0199",
        booking_url="https://example.test/book",
        official_url="https://example.test/camp",
    )
    brief = build_campground_brief_v3(detail, generated_at=1_780_000_100)

    assert any(item["id"] == "max_rig_length" and item["value"] == "45 ft" for item in brief["access"])
    assert any(item["id"] == "hookups" for item in brief["access"])
    assert any(item["id"] == "phone" for item in brief["booking_contact"])
    assert any(item["id"] == "booking_url" for item in brief["booking_contact"])


def test_sparse_brief_is_useful_without_generic_prose_or_invented_facts():
    brief = build_campground_brief_v3({
        "id": "osm_node_42",
        "name": "Mapped Camp",
        "land_type": "Campground",
        "source": "osm",
        "site_types": ["Campground"],
        "amenities": [],
        "reservable": False,
    }, generated_at=1_780_000_100)

    text = json.dumps(brief)
    assert brief["evidence_status"] == "limited"
    assert _fact_values(brief) == {
        "camp_type": "Campground",
        "reservability": "Not listed as reservable",
    }
    assert "Operating season" in brief["unavailable"]
    assert "Maximum rig length" in brief["unavailable"]
    assert "confirm current" not in text.casefold()
    assert "check local" not in text.casefold()


def test_revision_is_bound_to_source_facts_not_input_list_order():
    first = build_campground_brief_v3(
        _recreation_detail(amenities=["Water", "Picnic tables"]),
        generated_at=1_780_000_100,
    )
    reordered = build_campground_brief_v3(
        _recreation_detail(amenities=["Picnic tables", "Water"]),
        generated_at=1_780_000_200,
    )
    changed = build_campground_brief_v3(
        _recreation_detail(amenities=["Picnic tables", "Water", "Showers"]),
        generated_at=1_780_000_200,
    )

    assert first["source_revision"] == reordered["source_revision"]
    assert first["source_revision"] != changed["source_revision"]


def test_endpoint_resolves_detail_server_side_and_tolerates_service_timeout():
    detail = _recreation_detail()
    with (
        patch.object(server, "_load_campsite_detail", new=AsyncMock(return_value=detail)) as load,
        patch.object(server, "get_service_places", new=AsyncMock(side_effect=TimeoutError)),
        patch.object(server, "deduct_credits") as deduct,
    ):
        result = asyncio.run(server.campground_brief_v3("place:ridb:234059", None))

    load.assert_awaited_once_with("place:ridb:234059", None)
    deduct.assert_not_called()
    assert result["entity"]["id"] == "234059"
    assert result["schema_version"] == "campground-brief-v3"
