import type { CampsiteDetail, CampsitePin } from '../api';
import type { SearchResultV2 } from '../searchV2';

export const kirchFlatSourceItemV1: CampsitePin = {
  id: 'place:usfs:usfs-sierra-sites-83a6b34b-07f9-40a0-a98b-68de9b7b81a8',
  place_id: 'place:usfs:usfs-sierra-sites-83a6b34b-07f9-40a0-a98b-68de9b7b81a8',
  provider_place_id: 'place:usfs:usfs-sierra-sites-83a6b34b-07f9-40a0-a98b-68de9b7b81a8',
  name: 'Kirch Flat Group Campground',
  lat: 36.87922085429918,
  lng: -119.14895040173735,
  tags: ['campground', 'usfs', 'forest service', 'Sierra National Forest'],
  land_type: 'usfs',
  description: 'At approximately 1,000 feet in elevation, Kirch Flat Campground resides on a large sandy flat area on the river edge of the scenic Kings River.',
  amenities: ['toilets'],
  site_types: ['campground'],
  photos: [],
  photo_url: '',
  reservable: false,
  url: 'https://www.fs.usda.gov/recarea/sierra/recarea/?recid=45570',
  official_url: 'https://www.fs.usda.gov/recarea/sierra/recarea/?recid=45570',
  booking_url: '',
  source: 'usfs',
  source_badge: 'USDA Forest Service',
  verified_source: 'USDA Forest Service',
  ada: false,
};

export const kirchFlatStoredDetailV1 = {
  ...kirchFlatSourceItemV1,
  requested_id: kirchFlatSourceItemV1.id,
  summary: kirchFlatSourceItemV1.description,
  cost: 'Single Site: $10 per night. $20 per night starting in 2026. Group Site: $100 per night',
  access_notes: 'Open',
  phone: '(559) 855-5355',
  activities: [],
  campsites: [],
  campsites_count: 0,
  photos: [],
  catalog_detail: true,
  planning_facts: [
    { key: 'place_type', label: 'Type', value: 'Campground' },
    { key: 'access', label: 'Access', value: 'Open' },
    { key: 'site_type', label: 'Site type', value: 'Group Campground' },
    { key: 'people_capacity', label: 'People capacity', value: '50 people' },
    { key: 'water', label: 'Water', value: 'No water is available' },
    { key: 'restrooms', label: 'Restrooms', value: 'Vault toilet(s)' },
    { key: 'phone', label: 'Phone', value: '(559) 855-5355' },
    { key: 'fees', label: 'Fees', value: 'Single Site: $10 per night. $20 per night starting in 2026. Group Site: $100 per night' },
    { key: 'operating_season', label: 'Operating season', value: 'All year' },
    { key: 'amenities', label: 'Amenities', value: 'toilets' },
  ],
} as CampsiteDetail & { catalog_detail: true; requested_id: string; summary: string };

export const portalDispersedSourceItemV1: CampsitePin = {
  id: 'place:usfs:usfs-sierra-sites-eba69754-2291-4aa7-858e-d85fc2d85b8b',
  place_id: 'place:usfs:usfs-sierra-sites-eba69754-2291-4aa7-858e-d85fc2d85b8b',
  name: 'PORTAL DISPERSED CAMP',
  lat: 37.317237212442286,
  lng: -119.07052015589264,
  land_type: 'Campground',
  description: 'PORTAL DISPERSED CAMP (Camping Area)',
  tags: ['campground', 'usfs', 'forest service', 'Sierra National Forest'],
  site_types: ['campground'],
  source: 'usfs',
  source_badge: 'USDA Forest Service',
  verified_source: 'USDA Forest Service',
  official_url: 'https://www.fs.usda.gov/recarea/sierra/recreation/camping-cabins',
  reservable: false,
  url: 'https://www.fs.usda.gov/recarea/sierra/recreation/camping-cabins',
  ada: false,
};

export const devilsGardenStoredDetailV1 = {
  id: 'place:ridb:234059',
  name: 'Devils Garden Campground',
  lat: 38.7769444,
  lng: -109.5891667,
  land_type: 'Campground',
  description: 'Devils Garden Campground is located in Arches National Park.',
  tags: ['Campground'],
  photos: [{
    url: 'https://cdn.recreation.gov/public/2019/10/03/14/33/234059_71942c9a-c262-4a4d-b664-46c1e2a47e48_1440.webp',
  }],
  amenities: [],
  site_types: ['Campground'],
  activities: ['Campground'],
  campsites: null,
  reviews: null,
  provider_notices: null,
  source: 'ridb',
  source_badge: 'Recreation.gov',
  verified_source: 'Recreation.gov',
  reservable: true,
  ada: false,
} as unknown as CampsiteDetail;

export const devilsGardenResolvedSearchResultV2: SearchResultV2 = {
  result_id: 'place:ridb:234059',
  canonical_place_id: 'place:ridb:234059',
  title: 'Devils Garden Campground',
  subtitle: 'Arches National Park, Utah',
  kind: 'campground',
  categories: ['campground'],
  coordinates: { lat: 38.7769444, lng: -109.5891667 },
  parent: 'Arches National Park',
  provenance: {
    provider: 'trailhead',
    source_label: 'Recreation.gov',
    provider_result_id: '234059',
    attribution: 'Recreation.gov',
    temporary_use_only: false,
  },
  persistence_policy: 'canonical',
  detail_ref: '/api/campsites/place%3Aridb%3A234059/detail',
  score: 100,
  match_reason: 'Exact canonical campground',
};

export const devilsGardenResolvedCampPinV1: CampsitePin = {
  id: 'place:ridb:234059',
  place_id: 'place:ridb:234059',
  provider_place_id: '234059',
  name: 'Devils Garden Campground',
  lat: 38.7769444,
  lng: -109.5891667,
  tags: ['campground', 'tent'],
  land_type: 'Campground',
  description: 'Arches National Park, Utah',
  reservable: false,
  cost: '',
  url: '',
  source: 'trailhead_search',
  source_badge: 'Recreation.gov',
  verified_source: 'Recreation.gov',
  ada: false,
};
