import type { CampsiteDetail, CampsitePin } from '../api';

export const kirchFlatSourceItemV1: CampsitePin = {
  id: 'place:usfs:usfs-sierra-sites-83a6b34b-07f9-40a0-a98b-68de9b7b81a8',
  place_id: 'place:usfs:usfs-sierra-sites-83a6b34b-07f9-40a0-a98b-68de9b7b81a8',
  provider_place_id: 'place:usfs:usfs-sierra-sites-83a6b34b-07f9-40a0-a98b-68de9b7b81a8',
  name: 'Kirch Flat Group Campground',
  lat: 36.87922085429918,
  lng: -119.14895040173735,
  tags: ['campground', 'usfs', 'forest service', 'Sierra National Forest', 'No Data'],
  land_type: 'usfs',
  description: 'At approximately 1,000 feet in elevation, Kirch Flat Campground resides on a large sandy flat area on the river edge of the scenic Kings River.',
  amenities: ['toilets'],
  site_types: ['campground'],
  photos: [{
    url: 'https://cdn.recreation.gov/public/2022/07/08/15/54/10182463_579ca7bd-50b9-49d7-8b0f-cef4e185ea41_700.webp',
    source: 'USDA Forest Service',
    caption: 'Kirch Flat Group Campground',
    credit: 'Recreation.gov',
  }],
  photo_url: 'https://cdn.recreation.gov/public/2022/07/08/15/54/10182463_579ca7bd-50b9-49d7-8b0f-cef4e185ea41_700.webp',
  reservable: true,
  url: 'https://apps.fs.usda.gov/arcx/rest/services/EDW/EDW_RecInfraRecreationSites_02/MapServer/0',
  official_url: 'https://apps.fs.usda.gov/arcx/rest/services/EDW/EDW_RecInfraRecreationSites_02/MapServer/0',
  booking_url: 'https://www.fs.usda.gov/recarea/sierra/recarea/?recid=45570',
  source: 'usfs',
  source_badge: 'USDA Forest Service',
  verified_source: 'USDA Forest Service',
  ada: false,
};

export const kirchFlatStoredDetailV1 = {
  ...kirchFlatSourceItemV1,
  requested_id: kirchFlatSourceItemV1.id,
  summary: kirchFlatSourceItemV1.description,
  cost: '',
  access_notes: 'Open',
  activities: [],
  campsites: [],
  campsites_count: 0,
  photos: kirchFlatSourceItemV1.photos,
  catalog_detail: true,
  planning_facts: [
    { key: 'place_type', label: 'Type', value: 'Campground' },
    { key: 'access', label: 'Access', value: 'Open' },
    { key: 'amenities', label: 'Amenities', value: 'toilets' },
  ],
} as CampsiteDetail & { catalog_detail: true; requested_id: string; summary: string };

export const portalDispersedSourceItemV1: CampsitePin = {
  id: 'place:usfs:usfs-sierra-sites-eba69754-2291-4aa7-858e-d85fc2d85b8b',
  place_id: 'place:usfs:usfs-sierra-sites-eba69754-2291-4aa7-858e-d85fc2d85b8b',
  name: 'PORTAL DISPERSED CAMP',
  lat: 37.317237212442286,
  lng: -119.07052015589264,
  land_type: 'Campground',
  description: 'PORTAL DISPERSED CAMP (Camping Area)',
  tags: ['campground', 'usfs', 'forest service', 'Sierra National Forest'],
  site_types: ['campground'],
  source: 'usfs',
  source_badge: 'USDA Forest Service',
  verified_source: 'USDA Forest Service',
  official_url: 'https://www.fs.usda.gov/recarea/sierra/recreation/camping-cabins',
  reservable: false,
  url: 'https://www.fs.usda.gov/recarea/sierra/recreation/camping-cabins',
  ada: false,
};

export const devilsGardenStoredDetailV1 = {
  id: 'place:ridb:234059',
  name: 'Devils Garden Campground',
  lat: 38.7769444,
  lng: -109.5891667,
  land_type: 'Campground',
  description: 'Devils Garden Campground is located in Arches National Park.',
  tags: ['Campground'],
  photos: [{
    url: 'https://cdn.recreation.gov/public/2019/10/03/14/33/234059_71942c9a-c262-4a4d-b664-46c1e2a47e48_1440.webp',
  }],
  amenities: [],
  site_types: ['Campground'],
  activities: ['Campground'],
  campsites: null,
  reviews: null,
  provider_notices: null,
  source: 'ridb',
  source_badge: 'Recreation.gov',
  verified_source: 'Recreation.gov',
  reservable: true,
  ada: false,
} as unknown as CampsiteDetail;
