"""Validation and cache policy for paid campground planning briefs.

The model researches the public place, but it never owns the public response.
This module accepts only concise claims with a citation that the server can
match to either the campground's source record or a URL returned by the web
search tool.
"""
from __future__ import annotations

import hashlib
import html
import json
import re
import time
from typing import Any
from urllib.parse import urlsplit, urlunsplit


CAMPGROUND_PLANNING_BRIEF_SCHEMA_VERSION = "campground-planning-brief-v1"
CAMPGROUND_PLANNING_BRIEF_POLICY_REVISION = "2026-07-26-grounding-2"
CAMPGROUND_PLANNING_BRIEF_TTL_SECONDS = 24 * 60 * 60

_SPACE_RE = re.compile(r"\s+")
_TAG_RE = re.compile(r"<[^>]+>")
_UNSUPPORTED_RE = re.compile(
    r"(?:"
    r"\bguaranteed\b|"
    r"\balways\s+(?:open|available|safe|quiet|passable)\b|"
    r"\b(?:safe|clear|open|passable)\s+(?:road|route|access)\b|"
    r"\bno\s+(?:hazards?|closures?|restrictions?|crowds?)\b|"
    r"\breliable\s+(?:cell|signal|service|coverage|water)\b|"
    r"\bwater\s+is\s+(?:safe|available|reliable)\b|"
    r"\b(?:chatgpt|openai|language model|web search|generated by ai)\b|"
    r"\b(?:supplied|provided|available)\s+evidence\b|"
    r"\b(?:the|your)\s+evidence(?:\s+context)?\b|"
    r"\bevidence\s+(?:context|record|field|says|shows|includes)\b"
    r")",
    re.IGNORECASE,
)

_SINGLE_SECTION_LIMITS = {
    "summary": 420,
    "best_time": 320,
    "access_and_rig": 360,
    "service_and_signal": 320,
}
_LIST_SECTION_LIMITS = {
    "look_out_for": (5, 260),
    "preparation": (5, 240),
    "nearby_context": (5, 240),
}


def _clean_text(value: object, max_chars: int) -> str:
    text = html.unescape(str(value or ""))
    text = _TAG_RE.sub(" ", text)
    text = text.replace("`", " ").replace("**", " ")
    text = _SPACE_RE.sub(" ", text).strip(" \t\r\n-*\u2022")
    if len(text) > max_chars:
        text = text[:max_chars].rsplit(" ", 1)[0].rstrip(" ,;:")
    return "" if _UNSUPPORTED_RE.search(text) else text


def _canonical_url(value: object) -> str:
    raw = str(value or "").strip()
    if not raw or len(raw) > 700:
        return ""
    try:
        parsed = urlsplit(raw)
    except ValueError:
        return ""
    if parsed.scheme.lower() not in {"http", "https"} or not parsed.netloc or "@" in parsed.netloc:
        return ""
    path = parsed.path.rstrip("/") or "/"
    return urlunsplit((parsed.scheme.lower(), parsed.netloc.lower(), path, parsed.query, ""))


def _source_rows(values: object) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    seen: set[str] = set()
    for value in values if isinstance(values, list) else []:
        if not isinstance(value, dict):
            continue
        url = _canonical_url(value.get("url"))
        if not url or url in seen:
            continue
        seen.add(url)
        title = _clean_text(value.get("title") or value.get("label"), 120)
        rows.append({"label": title or urlsplit(url).netloc, "url": url})
        if len(rows) == 16:
            break
    return rows


def campground_planning_source_revision(evidence: dict[str, Any]) -> str:
    canonical = json.dumps(
        {
            "policy_revision": CAMPGROUND_PLANNING_BRIEF_POLICY_REVISION,
            "evidence": evidence,
        },
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _source_supports_field(source: dict[str, str], field: str) -> bool:
    """Keep narrowly scoped datasets from citing unrelated planning claims."""
    try:
        host = urlsplit(source.get("url") or "").netloc.casefold()
    except ValueError:
        host = ""
    label = str(source.get("label") or "").casefold()
    signal_only = host == "fcc.gov" or host.endswith(".fcc.gov") or "fcc " in f"{label} "
    return field == "service_and_signal" if signal_only else True


def campground_planning_evidence(
    factual_brief: dict[str, Any],
) -> dict[str, Any]:
    """Return the bounded, source-owned context sent to the research model."""
    entity = factual_brief.get("entity") if isinstance(factual_brief.get("entity"), dict) else {}
    source_rows = _source_rows(factual_brief.get("sources"))
    return {
        "entity": {
            "id": _clean_text(entity.get("id"), 180),
            "name": _clean_text(entity.get("name"), 160) or "Campground",
            "lat": entity.get("lat"),
            "lng": entity.get("lng"),
        },
        "facts": factual_brief.get("facts") if isinstance(factual_brief.get("facts"), list) else [],
        "site_types": factual_brief.get("site_types") if isinstance(factual_brief.get("site_types"), list) else [],
        "access": factual_brief.get("access") if isinstance(factual_brief.get("access"), list) else [],
        "amenities": factual_brief.get("amenities") if isinstance(factual_brief.get("amenities"), list) else [],
        "conditions": factual_brief.get("conditions") if isinstance(factual_brief.get("conditions"), list) else [],
        "booking_contact": factual_brief.get("booking_contact") if isinstance(factual_brief.get("booking_contact"), list) else [],
        "mobile_coverage": factual_brief.get("mobile_coverage") if isinstance(factual_brief.get("mobile_coverage"), dict) else {},
        "nearby_services": factual_brief.get("nearby_services") if isinstance(factual_brief.get("nearby_services"), list) else [],
        "nearby_places": factual_brief.get("nearby_places") if isinstance(factual_brief.get("nearby_places"), list) else [],
        "unavailable": factual_brief.get("unavailable") if isinstance(factual_brief.get("unavailable"), list) else [],
        "sources": source_rows,
        "factual_source_revision": str(factual_brief.get("source_revision") or ""),
    }


def _cited_text(
    raw: object,
    *,
    max_chars: int,
    allowed_urls: dict[str, dict[str, str]],
) -> tuple[str, list[str]]:
    if not isinstance(raw, dict):
        return "", []
    text = _clean_text(raw.get("text"), max_chars)
    citations: list[str] = []
    for candidate in raw.get("source_urls") if isinstance(raw.get("source_urls"), list) else []:
        url = _canonical_url(candidate)
        if url and url in allowed_urls and url not in citations:
            citations.append(url)
    if not text or not citations:
        return "", []
    return text, citations[:4]


def build_campground_planning_brief(
    generated: dict[str, Any],
    evidence: dict[str, Any],
    research_sources: list[dict[str, Any]],
    *,
    now: int | None = None,
) -> dict[str, Any]:
    """Validate the model result and return the public, provider-neutral brief."""
    now = int(time.time()) if now is None else int(now)
    evidence_sources = _source_rows(evidence.get("sources"))
    web_sources = _source_rows(research_sources)
    allowed_rows = evidence_sources + web_sources
    allowed_urls = {row["url"]: row for row in allowed_rows}

    field_sources: dict[str, list[str]] = {}
    response: dict[str, Any] = {}
    for field, limit in _SINGLE_SECTION_LIMITS.items():
        field_urls = {
            url: row
            for url, row in allowed_urls.items()
            if _source_supports_field(row, field)
        }
        text, urls = _cited_text(generated.get(field), max_chars=limit, allowed_urls=field_urls)
        response[field] = text
        if urls:
            field_sources[field] = urls

    for field, (item_limit, char_limit) in _LIST_SECTION_LIMITS.items():
        field_urls = {
            url: row
            for url, row in allowed_urls.items()
            if _source_supports_field(row, field)
        }
        items: list[str] = []
        urls_for_field: list[str] = []
        for raw in generated.get(field) if isinstance(generated.get(field), list) else []:
            text, urls = _cited_text(raw, max_chars=char_limit, allowed_urls=field_urls)
            if not text or text.casefold() in {item.casefold() for item in items}:
                continue
            items.append(text)
            for url in urls:
                if url not in urls_for_field:
                    urls_for_field.append(url)
            if len(items) == item_limit:
                break
        response[field] = items
        if urls_for_field:
            field_sources[field] = urls_for_field[:8]

    if not any(
        response.get(field)
        for field in (*_SINGLE_SECTION_LIMITS.keys(), *_LIST_SECTION_LIMITS.keys())
    ):
        raise ValueError("The researched brief did not contain source-backed planning guidance")

    used_urls = {
        url
        for urls in field_sources.values()
        for url in urls
    }
    public_sources = [
        row for row in allowed_rows
        if row["url"] in used_urls
    ]
    deduped_sources: list[dict[str, str]] = []
    seen: set[str] = set()
    for row in public_sources:
        if row["url"] in seen:
            continue
        seen.add(row["url"])
        deduped_sources.append(row)

    entity = evidence.get("entity") if isinstance(evidence.get("entity"), dict) else {}
    source_revision = campground_planning_source_revision(evidence)
    return {
        "schema_version": CAMPGROUND_PLANNING_BRIEF_SCHEMA_VERSION,
        "entity": {
            "id": _clean_text(entity.get("id"), 180),
            "name": _clean_text(entity.get("name"), 160) or "Campground",
        },
        **response,
        "sources": deduped_sources[:12],
        "field_sources": field_sources,
        "source_revision": source_revision,
        "generated_at": now,
        "expires_at": now + CAMPGROUND_PLANNING_BRIEF_TTL_SECONDS,
    }


def cached_campground_planning_brief(
    cached: object,
    evidence: dict[str, Any],
    *,
    now: int | None = None,
) -> dict[str, Any] | None:
    if not isinstance(cached, dict):
        return None
    now = int(time.time()) if now is None else int(now)
    if cached.get("schema_version") != CAMPGROUND_PLANNING_BRIEF_SCHEMA_VERSION:
        return None
    if cached.get("source_revision") != campground_planning_source_revision(evidence):
        return None
    try:
        if int(cached.get("expires_at") or 0) <= now:
            return None
    except (TypeError, ValueError):
        return None
    return cached
