import type { ExplorePlaceProfile, ExploreSourcePackItem, ExploreTrailCard } from '@/lib/api';

type WaterfallSeed = {
  title: string;
  state: string;
  region: string;
  lat: number;
  lng: number;
  image: string;
  officialUrl: string;
  wikiUrl: string;
  height: string;
  access: string;
  season: string;
  safety: string;
  summary: string;
  highlight: string;
};

type TrailAreaSeed = {
  id: string;
  title: string;
  state: string;
  region: string;
  lat: number;
  lng: number;
  image: string;
  officialUrl: string;
  parkCode: string;
  summary: string;
  highlight: string;
  access: string;
  season: string;
  safety: string;
  aliases: string[];
  rank: number;
  trails: ExploreTrailCard[];
};

const LAST_UPDATED = 1781496931;
const YOSEMITE_PARK_URL = 'https://www.nps.gov/yose/index.htm';
const YOSEMITE_TRAILS_URL = 'https://www.nps.gov/yose/planyourvisit/hiking.htm';
const YOSEMITE_THINGS_TO_DO_URL = 'https://www.nps.gov/yose/planyourvisit/things2do.htm';
const YOSEMITE_CAMPING_URL = 'https://www.nps.gov/yose/planyourvisit/camping.htm';
const YOSEMITE_LODGING_URL = 'https://www.nps.gov/yose/planyourvisit/lodging.htm';
const YOSEMITE_VISITOR_URL = 'https://www.nps.gov/yose/planyourvisit/visitorcenters.htm';
const YOSEMITE_FALLS_IMAGE = 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Yosemite_falls_winter_2010.JPG/960px-Yosemite_falls_winter_2010.JPG';
const VERNAL_FALL_IMAGE = 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Vernal_Fall%2C_Yosemite_NP%2C_CA%2C_US_-_Diliff.jpg/960px-Vernal_Fall%2C_Yosemite_NP%2C_CA%2C_US_-_Diliff.jpg';
const HALF_DOME_IMAGE = 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Half_dome_yosemite_nationalpark.JPG/1280px-Half_dome_yosemite_nationalpark.JPG';
const MIRROR_LAKE_IMAGE = 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Yosemite_national_park_mirror_lake_2010u.JPG/1280px-Yosemite_national_park_mirror_lake_2010u.JPG';
const GLACIER_POINT_IMAGE = 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Glacier_Point_at_Sunset%2C_Yosemite_NP%2C_CA%2C_US_-_Diliff.jpg/1280px-Glacier_Point_at_Sunset%2C_Yosemite_NP%2C_CA%2C_US_-_Diliff.jpg';
const MARIPOSA_GROVE_IMAGE = 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Grizzly_Giant%2C_Mariposa_Grove%2C_Yosemite_National_Park_-_June_2022.jpg/960px-Grizzly_Giant%2C_Mariposa_Grove%2C_Yosemite_National_Park_-_June_2022.jpg';
const ZION_IMAGE = 'https://upload.wikimedia.org/wikipedia/commons/1/10/Zion_angels_landing_view.jpg';
const GRAND_CANYON_IMAGE = 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Dawn_on_the_S_rim_of_the_Grand_Canyon_%288645178272%29.jpg';
const GLACIER_IMAGE = 'https://upload.wikimedia.org/wikipedia/commons/5/51/Mountain_Goat_at_Hidden_Lake.jpg';
const ROCKY_MOUNTAIN_IMAGE = 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Rocky_Mountain_National_Park_in_September_2011_-_Glacier_Gorge_from_Bear_Lake.JPG/960px-Rocky_Mountain_National_Park_in_September_2011_-_Glacier_Gorge_from_Bear_Lake.JPG';
const GRAND_TETON_IMAGE = 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Barns_grand_tetons.jpg';
const SMOKIES_IMAGE = 'https://upload.wikimedia.org/wikipedia/commons/b/bc/View_atop_Cliff_Tops_on_Mount_LeConte%2C_GSMNP%2C_TN.jpg';
const ACADIA_IMAGE = 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Acadia_National_Park_02.JPG';

const YOSEMITE_TRAILS: ExploreTrailCard[] = [
  {
    id: 'yosemite-mist-trail',
    title: 'Mist Trail',
    difficulty: 'Easy',
    distance_mi: 3.2,
    route_type: 'Out & Back',
    elevation_gain_ft: 700,
    typical_time: '2-3 hrs',
    area: 'Yosemite Valley',
    image_url: VERNAL_FALL_IMAGE,
    summary: 'Close-up Vernal Fall access with mist, granite steps, and big valley views.',
    description: 'A popular Yosemite Valley hike that climbs toward Vernal Fall. Expect wet steps in high flow and heavy use on peak days.',
    best_season: 'Spring to early summer flow',
    dogs: 'Not allowed',
    bikes: 'Not allowed',
    tags: ['Waterfalls', 'Popular'],
    highlights: ['Waterfalls', 'Scenic Views', 'Wildflowers', 'Family Friendly'],
    lat: 37.7325,
    lng: -119.5586,
    source_url: 'https://www.nps.gov/yose/planyourvisit/vernalnevadatrail.htm',
  },
  {
    id: 'yosemite-half-dome',
    title: 'Half Dome',
    difficulty: 'Hard',
    distance_mi: 14.2,
    route_type: 'Out & Back',
    elevation_gain_ft: 4800,
    typical_time: '10-12 hrs',
    area: 'High Country',
    image_url: HALF_DOME_IMAGE,
    summary: 'Permit-only cable route with major elevation, exposure, and all-day commitment.',
    description: 'Half Dome is a long, exposed Yosemite classic. Permits, weather, water, and turnaround time matter before starting.',
    best_season: 'Cable season only',
    dogs: 'Not allowed',
    bikes: 'Not allowed',
    tags: ['Iconic', 'Challenging'],
    highlights: ['Summit', 'Permits', 'Exposure', 'Big Views'],
    lat: 37.7460,
    lng: -119.5332,
    source_url: 'https://www.nps.gov/yose/planyourvisit/halfdome.htm',
  },
  {
    id: 'yosemite-mirror-lake-loop',
    title: 'Mirror Lake Loop',
    difficulty: 'Easy',
    distance_mi: 2.0,
    route_type: 'Loop',
    elevation_gain_ft: 100,
    typical_time: '1-2 hrs',
    area: 'Yosemite Valley',
    image_url: MIRROR_LAKE_IMAGE,
    summary: 'Easy valley walk to seasonal water and Half Dome reflections.',
    description: 'Mirror Lake is a low-effort Yosemite Valley stop with seasonal water, shaded walking, and easy add-on distance.',
    best_season: 'Spring and early summer',
    dogs: 'Paved section only',
    bikes: 'Paved section only',
    tags: ['Family Friendly', 'Scenic'],
    highlights: ['Lake', 'Reflections', 'Easy Walk', 'Half Dome'],
    lat: 37.7485,
    lng: -119.5491,
    source_url: 'https://www.nps.gov/yose/planyourvisit/mirrorlaketrail.htm',
  },
  {
    id: 'yosemite-upper-yosemite-fall',
    title: 'Upper Yosemite Fall Trail',
    difficulty: 'Hard',
    distance_mi: 7.2,
    route_type: 'Out & Back',
    elevation_gain_ft: 2700,
    typical_time: '6-8 hrs',
    area: 'Yosemite Valley',
    image_url: YOSEMITE_FALLS_IMAGE,
    summary: 'Steep climb to the top of Yosemite Falls with exposed switchbacks.',
    description: 'A demanding valley climb with heat, drop-offs, and major payoff views. Start early and carry enough water.',
    best_season: 'Spring to early summer flow',
    dogs: 'Not allowed',
    bikes: 'Not allowed',
    tags: ['Waterfalls', 'Climb'],
    highlights: ['Waterfalls', 'Valley Views', 'Steep Grade', 'Exposure'],
    lat: 37.7426,
    lng: -119.6024,
    source_url: 'https://www.nps.gov/yose/planyourvisit/yosemitefallstrail.htm',
  },
  {
    id: 'yosemite-taft-point',
    title: 'Taft Point & The Fissures',
    difficulty: 'Easy',
    distance_mi: 2.2,
    route_type: 'Out & Back',
    elevation_gain_ft: 200,
    typical_time: '1-2 hrs',
    area: 'Glacier Point Road',
    image_url: GLACIER_POINT_IMAGE,
    summary: 'Short forest approach to cliff-edge views and deep granite fissures.',
    description: 'Taft Point is short but exposed. Stay back from cliff edges and check Glacier Point Road status before driving up.',
    best_season: 'Road-open season',
    dogs: 'Not allowed',
    bikes: 'Not allowed',
    tags: ['Scenic', 'Cliff Views'],
    highlights: ['Fissures', 'Views', 'Sunset', 'Short Hike'],
    lat: 37.7128,
    lng: -119.6047,
    source_url: YOSEMITE_TRAILS_URL,
  },
  {
    id: 'yosemite-mariposa-grove',
    title: 'Mariposa Grove',
    difficulty: 'Easy',
    distance_mi: 2.0,
    route_type: 'Loop',
    elevation_gain_ft: 300,
    typical_time: '1.5-3 hrs',
    area: 'South Entrance',
    image_url: MARIPOSA_GROVE_IMAGE,
    summary: 'Giant sequoia grove walks with longer loop options beyond the arrival area.',
    description: 'Mariposa Grove gives Yosemite a forest-focused trail day. Shuttle access, snow, and restoration closures can affect plans.',
    best_season: 'Spring through fall',
    dogs: 'Not allowed',
    bikes: 'Not allowed',
    tags: ['Sequoias', 'Family Friendly'],
    highlights: ['Giant Sequoias', 'Forest', 'Loop Options', 'Shade'],
    lat: 37.5116,
    lng: -119.6008,
    source_url: 'https://www.nps.gov/yose/planyourvisit/mg.htm',
  },
];

const TRAIL_AREA_SEEDS: TrailAreaSeed[] = [
  {
    id: 'explore:trails:zion-canyon-trails',
    title: 'Zion Canyon Trails',
    state: 'UT',
    region: 'Zion National Park',
    lat: 37.2982,
    lng: -112.9478,
    image: ZION_IMAGE,
    officialUrl: 'https://www.nps.gov/zion/planyourvisit/zion-canyon-trail-descriptions.htm',
    parkCode: 'zion',
    rank: 13,
    season: 'Spring and fall are usually best',
    access: 'Zion Canyon shuttle, seasonal parking limits, permits for some routes',
    safety: 'Heat, flash floods, exposure, water crossings, and permit rules matter',
    summary: 'Zion Canyon hikes mix paved river walks, canyon water routes, cliff exposure, and big-view climbs.',
    highlight: 'Compare Angels Landing, The Narrows, Emerald Pools, and Canyon Overlook from one trail list.',
    aliases: ['zion trails', 'angels landing', 'the narrows', 'emerald pools', 'zion canyon hikes'],
    trails: [
      {
        id: 'zion-angels-landing',
        title: 'Angels Landing',
        difficulty: 'Hard',
        distance_mi: 5.4,
        route_type: 'Out & Back',
        elevation_gain_ft: 1488,
        typical_time: '4-5 hrs',
        area: 'Zion Canyon',
        image_url: ZION_IMAGE,
        summary: 'Permit-controlled cliff route with chains, exposure, and major canyon views.',
        description: 'A high-exposure Zion classic. Check permit status, weather, wind, heat, and your comfort with steep drop-offs before committing.',
        best_season: 'Spring and fall',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Permit', 'Exposure'],
        highlights: ['Big Views', 'Exposure', 'Permits', 'Steep Grade'],
        lat: 37.2692,
        lng: -112.9477,
        source_url: 'https://www.nps.gov/zion/planyourvisit/angels-landing-hiking-permits.htm',
      },
      {
        id: 'zion-narrows',
        title: 'The Narrows',
        difficulty: 'Hard',
        distance_mi: 9.4,
        route_type: 'Out & Back',
        elevation_gain_ft: 330,
        typical_time: '4-8 hrs',
        area: 'Temple of Sinawava',
        image_url: ZION_IMAGE,
        summary: 'Virgin River canyon walk where flow, flash-flood risk, and water temperature decide the day.',
        description: 'Plan The Narrows around river flow, flash-flood forecast, cold-water gear, daylight, and shuttle timing.',
        best_season: 'Late spring through fall',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['River', 'Slot Canyon'],
        highlights: ['Water', 'Canyon Walls', 'Weather Check', 'Shuttle'],
        lat: 37.2858,
        lng: -112.9470,
        source_url: 'https://www.nps.gov/zion/planyourvisit/thenarrows.htm',
      },
      {
        id: 'zion-emerald-pools',
        title: 'Emerald Pools',
        difficulty: 'Moderate',
        distance_mi: 3.0,
        route_type: 'Loop',
        elevation_gain_ft: 620,
        typical_time: '2-4 hrs',
        area: 'Zion Lodge',
        image_url: ZION_IMAGE,
        summary: 'Layered pool and waterfall route with short options near Zion Lodge.',
        description: 'A flexible canyon hike that can be shortened or extended. Expect crowds, wet rock, and closure checks after storms.',
        best_season: 'Spring and fall',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Waterfalls', 'Flexible'],
        highlights: ['Pools', 'Waterfalls', 'Family Options', 'Shade'],
        lat: 37.2520,
        lng: -112.9561,
        source_url: 'https://www.nps.gov/zion/planyourvisit/zion-canyon-trail-descriptions.htm',
      },
      {
        id: 'zion-canyon-overlook',
        title: 'Canyon Overlook Trail',
        difficulty: 'Moderate',
        distance_mi: 1.0,
        route_type: 'Out & Back',
        elevation_gain_ft: 160,
        typical_time: '1 hr',
        area: 'Zion-Mount Carmel Highway',
        image_url: ZION_IMAGE,
        summary: 'Short ledge-and-overlook hike above the Zion tunnel with big canyon payoff.',
        description: 'A short but exposed trail with tight parking. Check tunnel-area traffic and stay back from edges.',
        best_season: 'Year-round, avoid icy edges',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Short Hike', 'Viewpoint'],
        highlights: ['Views', 'Short Hike', 'Exposure', 'Sunrise'],
        lat: 37.2133,
        lng: -112.9400,
        source_url: 'https://www.nps.gov/zion/planyourvisit/zion-canyon-trail-descriptions.htm',
      },
    ],
  },
  {
    id: 'explore:trails:grand-canyon-corridor-trails',
    title: 'Grand Canyon Corridor Trails',
    state: 'AZ',
    region: 'Grand Canyon National Park',
    lat: 36.0570,
    lng: -112.1431,
    image: GRAND_CANYON_IMAGE,
    officialUrl: 'https://www.nps.gov/grca/planyourvisit/day-hiking.htm',
    parkCode: 'grca',
    rank: 14,
    season: 'Spring and fall are usually best',
    access: 'South Rim shuttle stops and corridor trailheads',
    safety: 'Heat, water, ice, exposure, and uphill return time are critical',
    summary: 'Grand Canyon corridor hikes are descent-first routes where turnaround discipline matters.',
    highlight: 'Compare Bright Angel, South Kaibab, Rim Trail, and Hermit Trail before choosing a canyon day.',
    aliases: ['grand canyon trails', 'bright angel', 'south kaibab', 'rim trail', 'hermit trail'],
    trails: [
      {
        id: 'grand-canyon-bright-angel',
        title: 'Bright Angel Trail',
        difficulty: 'Hard',
        distance_mi: 9.3,
        route_type: 'Out & Back',
        elevation_gain_ft: 3060,
        typical_time: '6-9 hrs',
        area: 'South Rim',
        image_url: GRAND_CANYON_IMAGE,
        summary: 'Historic corridor trail with steep canyon descent and a demanding climb back out.',
        description: 'Turn around early unless you are prepared for heat, elevation, water planning, and the full uphill return.',
        best_season: 'Spring and fall',
        dogs: 'Not allowed below rim',
        bikes: 'Not allowed',
        tags: ['Canyon', 'Water Planning'],
        highlights: ['Canyon Views', 'Steep Grade', 'Heat Risk', 'Water Stops'],
        lat: 36.0570,
        lng: -112.1431,
        source_url: 'https://www.nps.gov/grca/planyourvisit/upload/BrightAngelTrail.pdf',
      },
      {
        id: 'grand-canyon-south-kaibab',
        title: 'South Kaibab Trail',
        difficulty: 'Hard',
        distance_mi: 6.0,
        route_type: 'Out & Back',
        elevation_gain_ft: 2040,
        typical_time: '4-6 hrs',
        area: 'Yaki Point',
        image_url: GRAND_CANYON_IMAGE,
        summary: 'Open ridge descent with huge views and no water on trail.',
        description: 'South Kaibab is exposed and dry. Use shuttle access, carry water, and turn around before the climb becomes a problem.',
        best_season: 'Spring and fall',
        dogs: 'Not allowed below rim',
        bikes: 'Not allowed',
        tags: ['Views', 'No Water'],
        highlights: ['Ridge Views', 'Sunrise', 'Exposure', 'Shuttle'],
        lat: 36.0520,
        lng: -112.0838,
        source_url: 'https://www.nps.gov/grca/planyourvisit/upload/SouthKaibabTrail.pdf',
      },
      {
        id: 'grand-canyon-rim-trail',
        title: 'Rim Trail',
        difficulty: 'Easy',
        distance_mi: 13.0,
        route_type: 'Point-to-Point',
        elevation_gain_ft: 550,
        typical_time: '2-6 hrs',
        area: 'South Rim',
        image_url: GRAND_CANYON_IMAGE,
        summary: 'Flexible rim walk with shuttle bailouts and repeated canyon viewpoints.',
        description: 'Use it for an easier canyon day, sunset stops, or short segments between viewpoints and shuttle stops.',
        best_season: 'Year-round, check ice',
        dogs: 'Allowed on leash above rim',
        bikes: 'Allowed on some paved sections',
        tags: ['Family Friendly', 'Views'],
        highlights: ['Viewpoints', 'Shuttle', 'Sunset', 'Easy Walk'],
        lat: 36.0612,
        lng: -112.1090,
        source_url: 'https://www.nps.gov/grca/planyourvisit/day-hiking.htm',
      },
      {
        id: 'grand-canyon-hermit-trail',
        title: 'Hermit Trail',
        difficulty: 'Hard',
        distance_mi: 7.0,
        route_type: 'Out & Back',
        elevation_gain_ft: 1700,
        typical_time: '5-7 hrs',
        area: 'Hermits Rest',
        image_url: GRAND_CANYON_IMAGE,
        summary: 'Rugged historic route with fewer services and more route-finding responsibility.',
        description: 'Hermit Trail is rougher than the main corridor. Check access, water, heat, and your turnaround plan.',
        best_season: 'Spring and fall',
        dogs: 'Not allowed below rim',
        bikes: 'Not allowed',
        tags: ['Rugged', 'Historic'],
        highlights: ['Canyon Views', 'Rugged Track', 'Solitude', 'Heat Risk'],
        lat: 36.0619,
        lng: -112.2125,
        source_url: 'https://www.nps.gov/grca/planyourvisit/day-hiking.htm',
      },
    ],
  },
  {
    id: 'explore:trails:glacier-high-country-trails',
    title: 'Glacier High Country Trails',
    state: 'MT',
    region: 'Glacier National Park',
    lat: 48.6969,
    lng: -113.7183,
    image: GLACIER_IMAGE,
    officialUrl: 'https://www.nps.gov/glac/planyourvisit/hikingthetrails.htm',
    parkCode: 'glac',
    rank: 15,
    season: 'Summer and early fall',
    access: 'Going-to-the-Sun Road, shuttles, bear-country trailheads',
    safety: 'Snow, storms, bears, exposure, and road access change quickly',
    summary: 'Glacier high-country hikes need snow, shuttle, bear, and storm checks before the trail decision.',
    highlight: 'Compare Highline, Grinnell Glacier, Hidden Lake, and Avalanche Lake from one trail list.',
    aliases: ['glacier trails', 'highline trail', 'grinnell glacier', 'hidden lake', 'avalanche lake'],
    trails: [
      {
        id: 'glacier-highline',
        title: 'Highline Trail',
        difficulty: 'Hard',
        distance_mi: 11.8,
        route_type: 'Point-to-Point',
        elevation_gain_ft: 1950,
        typical_time: '6-8 hrs',
        area: 'Logan Pass',
        image_url: GLACIER_IMAGE,
        summary: 'Big-view alpine traverse from Logan Pass with exposure and shuttle logistics.',
        description: 'Highline depends on snow clearance, shuttle timing, weather, and comfort with narrow exposed sections.',
        best_season: 'Mid-summer to early fall',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Alpine', 'Shuttle'],
        highlights: ['Big Views', 'Exposure', 'Wildflowers', 'Wildlife'],
        lat: 48.6967,
        lng: -113.7184,
        source_url: 'https://www.nps.gov/glac/planyourvisit/hikingthetrails.htm',
      },
      {
        id: 'glacier-grinnell-glacier',
        title: 'Grinnell Glacier Trail',
        difficulty: 'Hard',
        distance_mi: 10.6,
        route_type: 'Out & Back',
        elevation_gain_ft: 1600,
        typical_time: '5-7 hrs',
        area: 'Many Glacier',
        image_url: GLACIER_IMAGE,
        summary: 'Lake-and-glacier route with strong scenery and serious weather exposure.',
        description: 'A signature Many Glacier hike. Check trail status, boat options, bear activity, and afternoon storm risk.',
        best_season: 'Summer and early fall',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Glacier', 'Lakes'],
        highlights: ['Glacier', 'Lakes', 'Wildlife', 'Big Views'],
        lat: 48.7976,
        lng: -113.6805,
        source_url: 'https://www.nps.gov/glac/planyourvisit/hikingthetrails.htm',
      },
      {
        id: 'glacier-hidden-lake',
        title: 'Hidden Lake Overlook',
        difficulty: 'Moderate',
        distance_mi: 2.7,
        route_type: 'Out & Back',
        elevation_gain_ft: 540,
        typical_time: '1.5-2.5 hrs',
        area: 'Logan Pass',
        image_url: GLACIER_IMAGE,
        summary: 'Boardwalk and alpine overlook route from Logan Pass.',
        description: 'A shorter alpine option with snowfields, wildlife closures, and fast-changing weather.',
        best_season: 'Summer and early fall',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Overlook', 'Wildlife'],
        highlights: ['Lake Views', 'Wildlife', 'Wildflowers', 'Short Hike'],
        lat: 48.6957,
        lng: -113.7175,
        source_url: 'https://www.nps.gov/glac/planyourvisit/hikingthetrails.htm',
      },
      {
        id: 'glacier-avalanche-lake',
        title: 'Avalanche Lake',
        difficulty: 'Moderate',
        distance_mi: 5.9,
        route_type: 'Out & Back',
        elevation_gain_ft: 750,
        typical_time: '3-4 hrs',
        area: 'Lake McDonald',
        image_url: GLACIER_IMAGE,
        summary: 'Forest and lake hike beneath steep walls and waterfall ribbons.',
        description: 'A popular lower-elevation option. Expect parking pressure and check for trail or wildlife closures.',
        best_season: 'Late spring through fall',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Lake', 'Forest'],
        highlights: ['Lake', 'Forest', 'Waterfalls', 'Family Options'],
        lat: 48.6795,
        lng: -113.8191,
        source_url: 'https://www.nps.gov/glac/planyourvisit/hikingthetrails.htm',
      },
    ],
  },
  {
    id: 'explore:trails:rocky-mountain-alpine-trails',
    title: 'Rocky Mountain Alpine Trails',
    state: 'CO',
    region: 'Rocky Mountain National Park',
    lat: 40.3106,
    lng: -105.6457,
    image: ROCKY_MOUNTAIN_IMAGE,
    officialUrl: 'https://www.nps.gov/romo/planyourvisit/hiking.htm',
    parkCode: 'romo',
    rank: 16,
    season: 'Summer and fall, snow checks outside season',
    access: 'Timed entry, Bear Lake corridor, alpine trailheads',
    safety: 'Altitude, lightning, snow, ice, and parking limits shape the day',
    summary: 'Rocky Mountain hikes range from easy lake loops to altitude-heavy alpine climbs.',
    highlight: 'Compare Bear Lake, Emerald Lake, Sky Pond, and Chasm Lake by effort and conditions.',
    aliases: ['rocky mountain trails', 'bear lake', 'emerald lake', 'sky pond', 'chasm lake'],
    trails: [
      {
        id: 'rocky-mountain-bear-lake',
        title: 'Bear Lake Loop',
        difficulty: 'Easy',
        distance_mi: 0.7,
        route_type: 'Loop',
        elevation_gain_ft: 50,
        typical_time: '30-60 min',
        area: 'Bear Lake',
        image_url: ROCKY_MOUNTAIN_IMAGE,
        summary: 'Short lake loop with mountain views and easy add-ons.',
        description: 'A simple scenic stop, but timed entry, shuttle use, ice, and parking still matter.',
        best_season: 'Year-round, check ice',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Family Friendly', 'Lake'],
        highlights: ['Lake', 'Views', 'Short Hike', 'Add-ons'],
        lat: 40.3137,
        lng: -105.6460,
        source_url: 'https://www.nps.gov/romo/planyourvisit/hiking.htm',
      },
      {
        id: 'rocky-mountain-emerald-lake',
        title: 'Emerald Lake',
        difficulty: 'Moderate',
        distance_mi: 3.6,
        route_type: 'Out & Back',
        elevation_gain_ft: 650,
        typical_time: '2-3 hrs',
        area: 'Bear Lake',
        image_url: ROCKY_MOUNTAIN_IMAGE,
        summary: 'Classic Bear Lake corridor chain of alpine lakes.',
        description: 'A popular route through Nymph, Dream, and Emerald Lakes. Check snow, ice, storms, and shuttle timing.',
        best_season: 'Summer and fall',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Lakes', 'Popular'],
        highlights: ['Lake Views', 'Alpine', 'Wildflowers', 'Snow Check'],
        lat: 40.3097,
        lng: -105.6650,
        source_url: 'https://www.nps.gov/romo/planyourvisit/hiking.htm',
      },
      {
        id: 'rocky-mountain-sky-pond',
        title: 'Sky Pond',
        difficulty: 'Hard',
        distance_mi: 9.5,
        route_type: 'Out & Back',
        elevation_gain_ft: 1780,
        typical_time: '5-7 hrs',
        area: 'Glacier Gorge',
        image_url: ROCKY_MOUNTAIN_IMAGE,
        summary: 'Alpine lake route with waterfalls, talus, and a steep final section.',
        description: 'Sky Pond is a committed day with altitude, storms, snow, and route conditions to check.',
        best_season: 'Summer and early fall',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Alpine', 'Waterfalls'],
        highlights: ['Waterfalls', 'Alpine Lake', 'Steep Grade', 'Storm Risk'],
        lat: 40.3080,
        lng: -105.6823,
        source_url: 'https://www.nps.gov/romo/planyourvisit/hiking.htm',
      },
      {
        id: 'rocky-mountain-chasm-lake',
        title: 'Chasm Lake',
        difficulty: 'Hard',
        distance_mi: 8.4,
        route_type: 'Out & Back',
        elevation_gain_ft: 2500,
        typical_time: '5-7 hrs',
        area: 'Longs Peak',
        image_url: ROCKY_MOUNTAIN_IMAGE,
        summary: 'High alpine route below Longs Peak with serious weather exposure.',
        description: 'Start early, watch lightning, and check snow and wind before choosing this route.',
        best_season: 'Summer and early fall',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Alpine', 'Exposure'],
        highlights: ['Alpine Lake', 'Longs Peak', 'Exposure', 'Early Start'],
        lat: 40.2511,
        lng: -105.6163,
        source_url: 'https://www.nps.gov/romo/planyourvisit/hiking.htm',
      },
    ],
  },
  {
    id: 'explore:trails:grand-teton-trailheads',
    title: 'Grand Teton Trailheads',
    state: 'WY',
    region: 'Grand Teton National Park',
    lat: 43.7904,
    lng: -110.6818,
    image: GRAND_TETON_IMAGE,
    officialUrl: 'https://www.nps.gov/grte/planyourvisit/hike.htm',
    parkCode: 'grte',
    rank: 17,
    season: 'Summer and fall',
    access: 'Jenny Lake, Lupine Meadows, and canyon trailheads',
    safety: 'Bears, afternoon storms, snow, and lake-shuttle timing matter',
    summary: 'Grand Teton trails stack lake walks, canyon climbs, alpine lakes, and longer crest options.',
    highlight: 'Compare Jenny Lake, Cascade Canyon, Taggart Lake, and Teton Crest access points.',
    aliases: ['grand teton trails', 'jenny lake', 'cascade canyon', 'taggart lake', 'teton crest'],
    trails: [
      {
        id: 'grand-teton-jenny-lake',
        title: 'Jenny Lake Loop',
        difficulty: 'Moderate',
        distance_mi: 7.5,
        route_type: 'Loop',
        elevation_gain_ft: 450,
        typical_time: '3-5 hrs',
        area: 'Jenny Lake',
        image_url: GRAND_TETON_IMAGE,
        summary: 'Lake loop with boat-shuttle shortcuts, waterfalls, and canyon add-ons.',
        description: 'Use Jenny Lake as a flexible day: full loop, boat shortcut, Hidden Falls, Inspiration Point, or Cascade Canyon add-on.',
        best_season: 'Summer and fall',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Lake', 'Flexible'],
        highlights: ['Lake', 'Waterfalls', 'Boat Shuttle', 'Views'],
        lat: 43.7527,
        lng: -110.7240,
        source_url: 'https://www.nps.gov/grte/planyourvisit/hike.htm',
      },
      {
        id: 'grand-teton-cascade-canyon',
        title: 'Cascade Canyon',
        difficulty: 'Hard',
        distance_mi: 9.0,
        route_type: 'Out & Back',
        elevation_gain_ft: 1100,
        typical_time: '5-7 hrs',
        area: 'Jenny Lake',
        image_url: GRAND_TETON_IMAGE,
        summary: 'Glacial canyon hike with big Teton walls and wildlife potential.',
        description: 'Plan around boat timing or extra lake miles, bear safety, storms, and snow lingering into summer.',
        best_season: 'Summer and fall',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Canyon', 'Wildlife'],
        highlights: ['Canyon', 'Wildlife', 'Big Views', 'Bear Country'],
        lat: 43.7704,
        lng: -110.7827,
        source_url: 'https://www.nps.gov/grte/planyourvisit/hike.htm',
      },
      {
        id: 'grand-teton-taggart-lake',
        title: 'Taggart Lake',
        difficulty: 'Moderate',
        distance_mi: 3.8,
        route_type: 'Loop',
        elevation_gain_ft: 420,
        typical_time: '2-3 hrs',
        area: 'Teton Park Road',
        image_url: GRAND_TETON_IMAGE,
        summary: 'Shorter lake loop with strong Teton reflections and easier logistics.',
        description: 'A good half-day hike with views, forest, lake shore, and less commitment than canyon routes.',
        best_season: 'Late spring through fall',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Lake', 'Views'],
        highlights: ['Reflections', 'Lake', 'Family Options', 'Views'],
        lat: 43.6991,
        lng: -110.7327,
        source_url: 'https://www.nps.gov/grte/planyourvisit/hike.htm',
      },
      {
        id: 'grand-teton-teton-crest',
        title: 'Teton Crest Access',
        difficulty: 'Hard',
        distance_mi: 35.0,
        route_type: 'Point-to-Point',
        elevation_gain_ft: 8000,
        typical_time: '3-5 days',
        area: 'Backcountry',
        image_url: GRAND_TETON_IMAGE,
        summary: 'Backcountry route family across alpine passes and canyon exits.',
        description: 'Treat this as a permit, shuttle, weather, snow, and bear-country planning project, not a casual day hike.',
        best_season: 'Summer and early fall',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Backcountry', 'Permit'],
        highlights: ['Alpine Passes', 'Permits', 'Big Views', 'Multi-day'],
        lat: 43.6578,
        lng: -110.8225,
        source_url: 'https://www.nps.gov/grte/planyourvisit/back.htm',
      },
    ],
  },
  {
    id: 'explore:trails:great-smoky-mountains-trails',
    title: 'Great Smoky Mountains Trails',
    state: 'TN',
    region: 'Great Smoky Mountains National Park',
    lat: 35.6118,
    lng: -83.4895,
    image: SMOKIES_IMAGE,
    officialUrl: 'https://www.nps.gov/grsm/planyourvisit/hiking.htm',
    parkCode: 'grsm',
    rank: 18,
    season: 'Spring through fall',
    access: 'Trailheads around Newfound Gap, Cades Cove, and Gatlinburg side roads',
    safety: 'Weather, stream crossings, black bears, and seasonal road closures matter',
    summary: 'Smokies trails range from waterfall walks to steep forest climbs and Appalachian Trail sections.',
    highlight: 'Compare Alum Cave, Laurel Falls, Chimney Tops, and Clingmans Dome area hikes.',
    aliases: ['smokies trails', 'great smoky mountains hikes', 'alum cave', 'laurel falls', 'chimney tops'],
    trails: [
      {
        id: 'smokies-alum-cave',
        title: 'Alum Cave Trail',
        difficulty: 'Hard',
        distance_mi: 10.0,
        route_type: 'Out & Back',
        elevation_gain_ft: 2700,
        typical_time: '6-8 hrs',
        area: 'Newfound Gap Road',
        image_url: SMOKIES_IMAGE,
        summary: 'Steep forest route to Mount LeConte access with bluffs and strong views.',
        description: 'Check weather, daylight, ice, and your turnaround plan if continuing beyond Alum Cave Bluffs.',
        best_season: 'Spring through fall',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Climb', 'Views'],
        highlights: ['Bluffs', 'Forest', 'Views', 'Steep Grade'],
        lat: 35.6289,
        lng: -83.4507,
        source_url: 'https://www.nps.gov/grsm/planyourvisit/hiking.htm',
      },
      {
        id: 'smokies-laurel-falls',
        title: 'Laurel Falls',
        difficulty: 'Easy',
        distance_mi: 2.6,
        route_type: 'Out & Back',
        elevation_gain_ft: 400,
        typical_time: '1.5-2 hrs',
        area: 'Little River Road',
        image_url: SMOKIES_IMAGE,
        summary: 'Popular paved waterfall walk with crowd and parking pressure.',
        description: 'A short waterfall route, but expect heavy use and check current trail work or closure notices.',
        best_season: 'Spring through fall',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Waterfalls', 'Popular'],
        highlights: ['Waterfalls', 'Family Options', 'Forest', 'Parking Check'],
        lat: 35.6720,
        lng: -83.5800,
        source_url: 'https://www.nps.gov/grsm/planyourvisit/hiking.htm',
      },
      {
        id: 'smokies-chimney-tops',
        title: 'Chimney Tops Trail',
        difficulty: 'Hard',
        distance_mi: 3.5,
        route_type: 'Out & Back',
        elevation_gain_ft: 1400,
        typical_time: '3-4 hrs',
        area: 'Newfound Gap Road',
        image_url: SMOKIES_IMAGE,
        summary: 'Short, steep climb with a protected overlook endpoint.',
        description: 'Steep grades, wet roots, and weather make this harder than the mileage suggests. Respect closure boundaries.',
        best_season: 'Spring through fall',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Steep', 'Viewpoint'],
        highlights: ['Views', 'Steep Grade', 'Forest', 'Weather Check'],
        lat: 35.6353,
        lng: -83.4694,
        source_url: 'https://www.nps.gov/grsm/planyourvisit/hiking.htm',
      },
      {
        id: 'smokies-clingmans-dome',
        title: 'Clingmans Dome',
        difficulty: 'Moderate',
        distance_mi: 1.0,
        route_type: 'Out & Back',
        elevation_gain_ft: 330,
        typical_time: '1 hr',
        area: 'Clingmans Dome Road',
        image_url: SMOKIES_IMAGE,
        summary: 'Short, steep paved climb to the highest viewpoint in the park.',
        description: 'Road season, fog, storms, and temperature swings decide whether this is worth the drive.',
        best_season: 'Road-open season',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Viewpoint', 'Short Hike'],
        highlights: ['Summit', 'Views', 'Road Status', 'Short Hike'],
        lat: 35.5629,
        lng: -83.4985,
        source_url: 'https://www.nps.gov/grsm/planyourvisit/clingmansdome.htm',
      },
    ],
  },
  {
    id: 'explore:trails:acadia-coastal-trails',
    title: 'Acadia Coastal Trails',
    state: 'ME',
    region: 'Acadia National Park',
    lat: 44.3386,
    lng: -68.2733,
    image: ACADIA_IMAGE,
    officialUrl: 'https://www.nps.gov/acad/planyourvisit/hiking.htm',
    parkCode: 'acad',
    rank: 19,
    season: 'Late spring through fall',
    access: 'Park Loop Road, Island Explorer shuttle, carriage roads, coastal trailheads',
    safety: 'Ladders, cliffs, fog, wet rock, tides, and parking limits matter',
    summary: 'Acadia hikes pack coast, granite, ladders, lakes, and summit views into short but serious routes.',
    highlight: 'Compare Ocean Path, Beehive, Precipice, and Jordan Pond routes before choosing the day.',
    aliases: ['acadia trails', 'beehive trail', 'precipice trail', 'ocean path', 'jordan pond'],
    trails: [
      {
        id: 'acadia-ocean-path',
        title: 'Ocean Path',
        difficulty: 'Easy',
        distance_mi: 4.4,
        route_type: 'Out & Back',
        elevation_gain_ft: 350,
        typical_time: '2-3 hrs',
        area: 'Park Loop Road',
        image_url: ACADIA_IMAGE,
        summary: 'Coastal walk linking Sand Beach, Thunder Hole, and Otter Point views.',
        description: 'A flexible coast route with shuttle options. Watch waves, slick rock, fog, and traffic along Park Loop Road.',
        best_season: 'Late spring through fall',
        dogs: 'Allowed on leash where permitted',
        bikes: 'Not allowed on trail',
        tags: ['Coast', 'Family Friendly'],
        highlights: ['Ocean Views', 'Short Stops', 'Sunrise', 'Shuttle'],
        lat: 44.3297,
        lng: -68.1834,
        source_url: 'https://www.nps.gov/acad/planyourvisit/hiking.htm',
      },
      {
        id: 'acadia-beehive',
        title: 'Beehive Loop',
        difficulty: 'Hard',
        distance_mi: 1.5,
        route_type: 'Loop',
        elevation_gain_ft: 520,
        typical_time: '1.5-2 hrs',
        area: 'Sand Beach',
        image_url: ACADIA_IMAGE,
        summary: 'Short iron-rung route with exposure above Sand Beach.',
        description: 'Do not treat the mileage as easy. Ladders, exposure, wet rock, and one-way flow matter.',
        best_season: 'Dry warm season',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Ladders', 'Exposure'],
        highlights: ['Exposure', 'Ocean Views', 'Ladders', 'Short Hike'],
        lat: 44.3313,
        lng: -68.1851,
        source_url: 'https://www.nps.gov/acad/planyourvisit/hiking.htm',
      },
      {
        id: 'acadia-precipice',
        title: 'Precipice Trail',
        difficulty: 'Hard',
        distance_mi: 2.5,
        route_type: 'Loop',
        elevation_gain_ft: 1050,
        typical_time: '2-3 hrs',
        area: 'Champlain Mountain',
        image_url: ACADIA_IMAGE,
        summary: 'Exposed rung-and-ladder climb with seasonal falcon closures.',
        description: 'Only choose Precipice in dry conditions and after checking closure status. Exposure is the point and the risk.',
        best_season: 'Dry warm season outside closures',
        dogs: 'Not allowed',
        bikes: 'Not allowed',
        tags: ['Ladders', 'Closure Check'],
        highlights: ['Exposure', 'Ladders', 'Views', 'Closure Check'],
        lat: 44.3508,
        lng: -68.1887,
        source_url: 'https://www.nps.gov/acad/planyourvisit/precipice-trail.htm',
      },
      {
        id: 'acadia-jordan-pond',
        title: 'Jordan Pond Path',
        difficulty: 'Moderate',
        distance_mi: 3.3,
        route_type: 'Loop',
        elevation_gain_ft: 220,
        typical_time: '1.5-2.5 hrs',
        area: 'Jordan Pond',
        image_url: ACADIA_IMAGE,
        summary: 'Lake loop with boardwalk sections and Bubble mountain views.',
        description: 'A scenic loop with fragile shore sections, wet boardwalk, and busy parking around Jordan Pond House.',
        best_season: 'Late spring through fall',
        dogs: 'Allowed on leash where permitted',
        bikes: 'Not allowed on trail',
        tags: ['Lake', 'Views'],
        highlights: ['Lake', 'Boardwalk', 'Views', 'Family Options'],
        lat: 44.3206,
        lng: -68.2547,
        source_url: 'https://www.nps.gov/acad/planyourvisit/hiking.htm',
      },
    ],
  },
];

const WATERFALLS: WaterfallSeed[] = [
  {
    title: 'Multnomah Falls',
    state: 'OR',
    region: 'Columbia River Gorge',
    lat: 45.57595,
    lng: -122.11536,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Multnomah_Falls_on_2_August_2012.jpg/1280px-Multnomah_Falls_on_2_August_2012.jpg',
    officialUrl: 'https://www.fs.usda.gov/recarea/crgnsa/recarea/?recid=30026',
    wikiUrl: 'https://en.wikipedia.org/wiki/Multnomah_Falls',
    height: '620 ft',
    access: 'Historic Columbia River Highway / I-84',
    season: 'Spring flow, year-round access checks',
    safety: 'Timed permits, icy paths, and closures can apply',
    summary: 'Oregon gorge waterfall with a two-tier drop, bridge viewpoint, and quick access from the Historic Columbia River Highway.',
    highlight: 'A real waterfall anchor for Columbia River Gorge routes, with bridge views, short walks, and permit-sensitive access.',
  },
  {
    title: 'Yosemite Falls',
    state: 'CA',
    region: 'Yosemite Valley',
    lat: 37.756845,
    lng: -119.596785,
    image: 'https://upload.wikimedia.org/wikipedia/commons/3/38/Yosemite_falls_winter_2010.JPG',
    officialUrl: 'https://www.nps.gov/yose/planyourvisit/yosemitefalls.htm',
    wikiUrl: 'https://en.wikipedia.org/wiki/Yosemite_Falls',
    height: '2,425 ft',
    access: 'Yosemite Valley trailheads',
    season: 'Peak flow is usually spring to early summer',
    safety: 'Mist, ice, heat, and exposed upper trail sections',
    summary: 'Yosemite Valley waterfall system with lower-view access and a strenuous upper-falls trail option.',
    highlight: 'A major Yosemite waterfall stop that can be planned as a short valley walk or a harder all-day climb.',
  },
  {
    title: 'Havasu Falls',
    state: 'AZ',
    region: 'Havasupai Reservation',
    lat: 36.255278,
    lng: -112.698056,
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/41/New_havasu_falls.JPG',
    officialUrl: 'https://theofficialhavasupaitribe.com/',
    wikiUrl: 'https://en.wikipedia.org/wiki/Havasu_Falls',
    height: '100 ft',
    access: 'Havasupai permit and campground reservation required',
    season: 'Permit windows and flash-flood risk drive timing',
    safety: 'Remote canyon travel, heat, water crossings, and tribal rules',
    summary: 'Blue-green Grand Canyon waterfall on Havasu Creek inside Havasupai tribal lands.',
    highlight: 'A permit-controlled canyon waterfall that belongs in planning only after access, dates, and tribal rules are confirmed.',
  },
  {
    title: 'Shoshone Falls',
    state: 'ID',
    region: 'Twin Falls',
    lat: 42.595278,
    lng: -114.400833,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Shoshone_Falls%2C_Idaho.jpg/1280px-Shoshone_Falls%2C_Idaho.jpg',
    officialUrl: 'https://www.tfid.org/309/Shoshone-Falls',
    wikiUrl: 'https://en.wikipedia.org/wiki/Shoshone_Falls',
    height: '212 ft',
    access: 'City park viewpoints near Twin Falls',
    season: 'Spring runoff is usually strongest',
    safety: 'Seasonal flow, road hours, and overlook edges',
    summary: 'Wide Snake River waterfall near Twin Falls with road-access viewpoints and seasonal flow changes.',
    highlight: 'A high-impact roadside waterfall stop that works well as a short scenic break on southern Idaho routes.',
  },
  {
    title: 'Tahquamenon Falls',
    state: 'MI',
    region: 'Upper Peninsula',
    lat: 46.574,
    lng: -85.256,
    image: 'https://upload.wikimedia.org/wikipedia/commons/7/74/Upper_Tahquamenon_Falls_Fall_2007.jpeg',
    officialUrl: 'https://www.michigan.gov/dnr/places/state-parks/tahquamenon-falls',
    wikiUrl: 'https://en.wikipedia.org/wiki/Tahquamenon_Falls',
    height: '50 ft',
    access: 'State park roads and boardwalk viewpoints',
    season: 'Four-season stop with winter access checks',
    safety: 'Snow, boardwalk ice, and river-edge conditions',
    summary: 'Upper Peninsula waterfall series known for amber water, broad views, and state-park trail access.',
    highlight: 'A Great Lakes waterfall anchor with easy viewpoints, forest trails, and useful campground context nearby.',
  },
  {
    title: 'Cumberland Falls',
    state: 'KY',
    region: 'Daniel Boone Country',
    lat: 36.83801,
    lng: -84.34444,
    image: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Cumberland_falls_2015_1.jpg',
    officialUrl: 'https://parks.ky.gov/corbin/parks/resort/cumberland-falls-state-resort-park',
    wikiUrl: 'https://en.wikipedia.org/wiki/Cumberland_Falls',
    height: '68 ft',
    access: 'State resort park viewpoints and trails',
    season: 'Moonbow nights need date and weather checks',
    safety: 'Wet rock, river levels, and overlook boundaries',
    summary: 'Kentucky waterfall on the Cumberland River, known for broad flow and occasional moonbow viewing.',
    highlight: 'A route-worthy waterfall stop with lodge, trail, and timing context around the famous moonbow window.',
  },
  {
    title: 'Amicalola Falls',
    state: 'GA',
    region: 'North Georgia Mountains',
    lat: 34.5675,
    lng: -84.244444,
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Amicalola_Falls.JPG',
    officialUrl: 'https://gastateparks.org/AmicalolaFalls',
    wikiUrl: 'https://en.wikipedia.org/wiki/Amicalola_Falls',
    height: '729 ft',
    access: 'State park roads, stairs, and approach trails',
    season: 'Good most of year; storms and ice change footing',
    safety: 'Steep stairs, slippery decks, and busy trailheads',
    summary: 'Tall Georgia waterfall in Amicalola Falls State Park with stair viewpoints and Appalachian approach-trail context.',
    highlight: 'A strong southeastern waterfall card with real trail decisions: stairs, overlooks, or longer approach-trail hiking.',
  },
  {
    title: 'Palouse Falls',
    state: 'WA',
    region: 'Palouse Falls State Park',
    lat: 46.663611,
    lng: -118.223611,
    image: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Palouse_Falls_%284634460573%29.jpg',
    officialUrl: 'https://parks.wa.gov/find-parks/state-parks/palouse-falls-state-park-heritage-site',
    wikiUrl: 'https://en.wikipedia.org/wiki/Palouse_Falls',
    height: '200 ft',
    access: 'State park overlook above canyon',
    season: 'Spring light and flow are common planning targets',
    safety: 'Cliff edges, heat, rattlesnakes, and limited shade',
    summary: 'Eastern Washington canyon waterfall with dramatic overlook access and desert-route exposure.',
    highlight: 'A waterfall card that should plan like a canyon viewpoint: short stop, big exposure, and careful edge safety.',
  },
  {
    title: 'Taughannock Falls',
    state: 'NY',
    region: 'Finger Lakes',
    lat: 42.545,
    lng: -76.606,
    image: 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Taughannock_Falls.JPG',
    officialUrl: 'https://parks.ny.gov/parks/taughannockfalls',
    wikiUrl: 'https://en.wikipedia.org/wiki/Taughannock_Falls_State_Park',
    height: '215 ft',
    access: 'State park gorge and overlook trails',
    season: 'Spring flow and fall color both work well',
    safety: 'Gorge trail closures, ice, and falling-rock zones',
    summary: 'Finger Lakes waterfall with gorge-route and overlook-route options inside a New York state park.',
    highlight: 'A waterfall stop with the trail-choice feel from the mock: easy overlook, gorge walk, or lake-side add-ons.',
  },
];

const YOSEMITE_PARK_HUB = buildYosemiteParkHub();
const YOSEMITE_TRAIL_AREA = buildYosemiteTrailArea();
const CURATED_TRAIL_AREAS = TRAIL_AREA_SEEDS.map(seed => buildTrailAreaPlace(seed));
const ALL_TRAIL_AREA_GUIDES = [YOSEMITE_TRAIL_AREA, ...CURATED_TRAIL_AREAS];
const TRAIL_AREA_BY_ID = new Map(ALL_TRAIL_AREA_GUIDES.map(place => [place.id, place]));
const TRAIL_AREA_BY_TITLE_STATE = new Map(
  ALL_TRAIL_AREA_GUIDES.map(place => [`${normalizeTitle(place.summary.title)}:${String(place.summary.state || '').toUpperCase()}`, place]),
);
const TRAIL_AREA_BY_REGION_TITLE = new Map(
  ALL_TRAIL_AREA_GUIDES.map(place => [normalizeTitle(String(place.summary.region || '')), place]),
);

export const CURATED_EXPLORE_PLACES: ExplorePlaceProfile[] = [
  YOSEMITE_PARK_HUB,
  YOSEMITE_TRAIL_AREA,
  ...CURATED_TRAIL_AREAS,
  ...WATERFALLS.map((seed, index) => buildWaterfallPlace(seed, index)),
];

export function mergeCuratedExplorePlaces(places: ExplorePlaceProfile[]) {
  const attachedGuideIds = new Set<string>();
  const enrichedPlaces = places.map(place => {
    const guide = curatedTrailAreaForPlace(place);
    if (guide && guide.id !== place.id) attachedGuideIds.add(guide.id);
    return guide ? withTrailAreaDetails(place, guide) : place;
  });
  const curatedPlaces = CURATED_EXPLORE_PLACES.filter(place => place.id !== YOSEMITE_TRAIL_AREA.id && !TRAIL_AREA_BY_ID.has(place.id));
  const orphanTrailAreas = ALL_TRAIL_AREA_GUIDES.filter(place => !attachedGuideIds.has(place.id));
  const indexByKey = new Map<string, number>();
  const merged: ExplorePlaceProfile[] = [];
  for (const place of [...enrichedPlaces, ...orphanTrailAreas, ...curatedPlaces]) {
    const keys = mergeKeysForPlace(place);
    const existingIndex = keys
      .map(key => indexByKey.get(key))
      .find(index => index != null);
    if (existingIndex != null) {
      const current = merged[existingIndex];
      if (curatedPlacePriority(place) > curatedPlacePriority(current)) {
        merged[existingIndex] = place;
        keys.forEach(key => indexByKey.set(key, existingIndex));
      }
      continue;
    }
    const nextIndex = merged.length;
    keys.forEach(key => indexByKey.set(key, nextIndex));
    merged.push(place);
  }
  return merged;
}

function curatedTrailAreaForPlace(place: ExplorePlaceProfile) {
  if (isYosemiteTrailPlace(place)) return YOSEMITE_TRAIL_AREA;
  const titleState = `${normalizeTitle(String(place.summary.title || ''))}:${String(place.summary.state || '').toUpperCase()}`;
  const titleOnly = normalizeTitle(String(place.summary.title || ''));
  return TRAIL_AREA_BY_ID.get(place.id) || TRAIL_AREA_BY_TITLE_STATE.get(titleState) || TRAIL_AREA_BY_REGION_TITLE.get(titleOnly) || null;
}

function mergeKeysForPlace(place: ExplorePlaceProfile) {
  const title = normalizeTitle(String(place.summary.title || ''));
  const state = String(place.summary.state || '').toUpperCase();
  const keys = new Set<string>([place.id, `${title}:${state}`]);
  if (isDestinationHubPlace(place)) keys.add(`hub:${title}`);
  if (isLooseYosemiteTrailPlace(place)) keys.add('yosemite-trails:CA');
  return Array.from(keys).filter(Boolean);
}

function isDestinationHubPlace(place: ExplorePlaceProfile) {
  const title = normalizeTitle(String(place.summary.title || ''));
  const categoryText = normalizeTitle([
    place.category,
    place.summary.category,
    place.summary.explore_group,
    ...(place.subcategories ?? []),
  ].filter(Boolean).join(' '));
  if (place.id.startsWith('place:nps:')) return true;
  if (/\b(national|state|provincial|regional|county)?\s*(park|monument|preserve|seashore|lakeshore|forest|wilderness|recreation area|reserve|historic site|historical park)\b/.test(title)) return true;
  if (/camp|trail|trailhead|visitor|parking|glamp|hut|lodg|tour|activity|climb/.test(categoryText)) return false;
  return false;
}

function curatedPlacePriority(place: ExplorePlaceProfile) {
  const text = JSON.stringify({
    id: place.id,
    quality: (place as any).quality,
    sources: place.sources,
    source_pack: place.source_pack,
    source_title: place.summary.source_title,
  }).toLowerCase();
  let score = 0;
  if (place.id.startsWith('place:nps:')) score += 1000;
  if (/national park service|nps|official/.test(text)) score += 220;
  if (place.source_pack?.things_to_do?.length) score += place.source_pack.things_to_do.length;
  if (place.source_pack?.things_to_see?.length) score += place.source_pack.things_to_see.length;
  if (place.source_pack?.campgrounds?.length) score += place.source_pack.campgrounds.length;
  if (place.summary.image_url || place.summary.thumbnail_url) score += 10;
  score -= Math.min(Number(place.summary.rank ?? 999999), 999999) / 100000;
  return score;
}

function isYosemiteTrailPlace(place: ExplorePlaceProfile) {
  const title = normalizeTitle(String(place.summary.title || ''));
  const state = String(place.summary.state || '').toUpperCase();
  const categoryText = normalizeTitle([
    place.summary.category,
    place.category,
    ...(Array.isArray(place.subcategories) ? place.subcategories : []),
  ].filter(Boolean).join(' '));
  return state === 'CA' && title.includes('yosemite') && title.includes('trail') && categoryText.includes('trail');
}

function isLooseYosemiteTrailPlace(place: ExplorePlaceProfile) {
  const title = normalizeTitle(String(place.summary.title || ''));
  const state = String(place.summary.state || '').toUpperCase();
  return state === 'CA' && title.includes('yosemite') && title.includes('trail');
}

function withTrailAreaDetails(place: ExplorePlaceProfile, guide: ExplorePlaceProfile): ExplorePlaceProfile {
  const guideTrails = (guide as any).trails ?? [];
  const placeSourcePack = place.source_pack ?? {};
  const guideSourcePack = guide.source_pack ?? {};
  const imageUrl = place.summary.image_url || guide.summary.image_url || place.summary.thumbnail_url || guide.summary.thumbnail_url || '';
  const preserveHubIdentity = isDestinationHubPlace(place);
  return {
    ...place,
    category: preserveHubIdentity ? place.category || guide.category : place.category || guide.category,
    subcategories: preserveHubIdentity
      ? (place.subcategories ?? [])
      : Array.from(new Set([...(place.subcategories ?? []), ...(guide.subcategories ?? [])])),
    quality: place.quality || guide.quality,
    quality_score: Math.max(Number((place as any).quality_score || 0), Number((guide as any).quality_score || 0)),
    search_aliases: Array.from(new Set([
      ...((place as any).search_aliases || []),
      ...((guide as any).search_aliases || []),
    ])),
    best_season: (place as any).best_season || (guide as any).best_season,
    access: (place as any).access || (guide as any).access,
    safety: (place as any).safety || (guide as any).safety,
    trails: guideTrails,
    sources: Array.from(new Set([...(place.sources ?? []), ...(guide.sources ?? [])] as any[])) as any,
    card: {
      ...((guide as any).card || {}),
      ...((place as any).card || {}),
      title: place.card?.title || place.summary.title,
      region: place.card?.region || place.summary.region || guide.card?.region,
      headline: place.card?.headline || guide.card?.headline,
      summary: place.card?.summary || guide.card?.summary,
      highlight: place.card?.highlight || guide.card?.highlight,
    },
    summary: {
      ...place.summary,
      id: place.summary.id || place.id,
      rank: Math.min(Number(place.summary.rank ?? 99), Number(guide.summary.rank ?? 12)),
      hero_rank: Math.min(Number(place.summary.hero_rank ?? place.summary.rank ?? 99), Number(guide.summary.hero_rank ?? 12)),
      tags: Array.from(new Set([...(place.summary.tags ?? []), ...(guide.summary.tags ?? [])])),
      badges: Array.from(new Set([...(place.summary.badges ?? []), ...(guide.summary.badges ?? [])])),
      hook: place.summary.hook || guide.summary.hook,
      short_description: place.summary.short_description || guide.summary.short_description,
      image_url: imageUrl,
      thumbnail_url: imageUrl || place.summary.thumbnail_url || guide.summary.thumbnail_url,
      image_credit: place.summary.image_credit || guide.summary.image_credit,
      image_license: place.summary.image_license || guide.summary.image_license,
      source_url: place.summary.source_url || guide.summary.source_url,
      source_title: place.summary.source_title || guide.summary.source_title,
    },
    profile: {
      ...guide.profile,
      ...place.profile,
      why_it_matters: place.profile.why_it_matters || guide.profile.why_it_matters,
      what_to_know: place.profile.what_to_know || guide.profile.what_to_know,
      best_time_to_stop: place.profile.best_time_to_stop || guide.profile.best_time_to_stop,
      access_notes: place.profile.access_notes || guide.profile.access_notes,
      nearby_context: place.profile.nearby_context || guide.profile.nearby_context,
    },
    audio_script: place.audio_script || guide.audio_script,
    wiki_extract: place.wiki_extract || guide.wiki_extract,
    source_pack: {
      ...guideSourcePack,
      ...placeSourcePack,
      photos: [
        ...((placeSourcePack.photos ?? []) as any[]),
        ...((guideSourcePack.photos ?? []) as any[]),
      ].filter((item, index, arr) => item?.url && arr.findIndex(other => other?.url === item.url) === index).slice(0, 16),
      things_to_do: [
        ...((placeSourcePack.things_to_do ?? []) as any[]),
        ...((guideSourcePack.things_to_do ?? []) as any[]),
      ].filter((item, index, arr) => item?.title && arr.findIndex(other => other?.title === item.title) === index),
      things_to_see: [
        ...((placeSourcePack.things_to_see ?? []) as any[]),
        ...((guideSourcePack.things_to_see ?? []) as any[]),
      ].filter((item, index, arr) => item?.title && arr.findIndex(other => other?.title === item.title) === index),
      sources: [
        ...((placeSourcePack.sources ?? []) as any[]),
        ...((guideSourcePack.sources ?? []) as any[]),
      ].filter((item, index, arr) => item?.url && arr.findIndex(other => other?.url === item.url) === index),
    },
    facts: {
      ...place.facts,
      ...guide.facts,
    },
    attribution: place.attribution || guide.attribution,
  };
}

function buildTrailAreaPlace(seed: TrailAreaSeed): ExplorePlaceProfile {
  const trails = seed.trails.map(trail => ({
    ...trail,
    image_url: trail.image_url || seed.image,
    source_url: trail.source_url || seed.officialUrl,
  }));
  const story = `${seed.title} brings the strongest hikes in ${seed.region} into one place. ${seed.summary} Check current access, closures, permits, weather, and daylight before starting.`;
  return {
    id: seed.id,
    category: 'Trails',
    subcategories: ['trails', 'hiking', 'trailheads'],
    quality: 'official_plus_open_media',
    quality_score: 90,
    search_aliases: seed.aliases,
    best_season: seed.season,
    access: { summary: seed.access },
    safety: { summary: seed.safety },
    trails,
    sources: [
      { title: `${seed.title} hiking`, publisher: 'National Park Service', url: seed.officialUrl, kind: 'official' },
      { title: `${seed.title} open imagery`, publisher: 'Wikimedia Commons', url: 'https://commons.wikimedia.org/', kind: 'open_media' },
    ],
    card: {
      title: seed.title,
      region: seed.region,
      headline: seed.highlight,
      summary: seed.summary,
      highlight: seed.highlight,
      facts: [`${trails.length} trails`, difficultyRangeLabel(trails), seed.season, 'Official trail pages'],
    },
    summary: {
      id: seed.id,
      title: seed.title,
      category: 'Trails',
      explore_group: 'trails',
      state: seed.state,
      region: seed.region,
      lat: seed.lat,
      lng: seed.lng,
      rank: seed.rank,
      hero_rank: seed.rank,
      tags: ['trails', 'hiking', 'views', 'trailheads', ...seed.aliases],
      badges: ['Trails'],
      hook: seed.highlight,
      short_description: seed.summary,
      thumbnail_url: seed.image,
      image_url: seed.image,
      image_credit: 'Wikimedia Commons',
      image_license: 'Open image reference',
      source_url: seed.officialUrl,
      source_title: 'National Park Service hiking page',
    },
    profile: {
      hook: `Explore trails in and around ${seed.region}.`,
      summary: seed.summary,
      story,
      why_it_matters: seed.highlight,
      what_to_know: seed.safety,
      best_time_to_stop: seed.season,
      access_notes: seed.access,
      nearby_context: 'Use the map to layer trailheads, campgrounds, parking, fuel, weather, and road access around these hikes.',
    },
    audio_script: story,
    wiki_extract: '',
    source_pack: {
      quality: 'official',
      primary: 'National Park Service',
      official_url: seed.officialUrl,
      nps_park_code: seed.parkCode,
      sources: [
        { title: `${seed.title} hiking`, publisher: 'National Park Service', url: seed.officialUrl, kind: 'official' },
        { title: `${seed.title} open images`, publisher: 'Wikimedia Commons', url: 'https://commons.wikimedia.org/', kind: 'open_media' },
      ],
      photos: trails.slice(0, 4).map(trail => ({ url: trail.image_url, caption: trail.title, credit: 'Wikimedia Commons' })),
      activities: ['Hiking', 'Viewpoints', 'Trailheads', 'Backcountry access'],
      things_to_do: trails.map(trail => ({
        kind: 'trail',
        source: 'National Park Service',
        source_id: trail.id,
        title: trail.title,
        description: trailSourcePackDescription(trail),
        url: trail.source_url || seed.officialUrl,
        lat: trail.lat,
        lng: trail.lng,
        image_url: trail.image_url,
        image_credit: 'Wikimedia Commons',
        source_label: 'National Park Service',
        category: `${trail.difficulty} ${trail.route_type}`,
        amenities: trail.highlights,
        distance_mi: trail.distance_mi,
      })),
      things_to_see: trails.slice(0, 3).map(trail => ({
        title: trail.title,
        description: trail.summary,
        url: trail.source_url || seed.officialUrl,
        lat: trail.lat,
        lng: trail.lng,
        image_url: trail.image_url,
        image_credit: 'Wikimedia Commons',
      })),
      source_note: 'Trail details use official land-manager pages and open image references. Check current trail status before starting.',
      license: 'Open image reference; verify media license at source.',
      image_asset: seed.image,
    },
    facts: {
      coordinates: `${seed.lat.toFixed(5)}, ${seed.lng.toFixed(5)}`,
      source_url: seed.officialUrl,
      source_title: 'National Park Service hiking page',
      official_url: seed.officialUrl,
      source_quality: 'official',
      last_updated: LAST_UPDATED,
    },
    attribution: 'National Park Service trail pages + Wikimedia Commons image references',
  };
}

function difficultyRangeLabel(trails: ExploreTrailCard[]) {
  const labels = new Set(trails.map(trail => trail.difficulty));
  if (labels.has('Easy') && labels.has('Hard')) return 'Easy - Hard';
  if (labels.has('Moderate') && labels.has('Hard')) return 'Moderate - Hard';
  return Array.from(labels).join(' / ') || 'Check difficulty';
}

function trailSourcePackDescription(trail: ExploreTrailCard) {
  const parts = [
    `${trail.distance_mi.toFixed(trail.distance_mi >= 10 ? 0 : 1)} mi · ${trail.route_type} · ${trail.difficulty}`,
    trail.summary,
    trail.description,
  ].map(part => String(part || '').trim().replace(/\.+$/, '')).filter(Boolean);
  return parts.length ? `${parts.join('. ')}.` : '';
}

function buildWaterfallPlace(seed: WaterfallSeed, index: number): ExplorePlaceProfile {
  const id = `explore:waterfalls:${normalizeTitle(seed.title)}`;
  const thingsToDo: ExploreSourcePackItem[] = [
    {
      title: 'Open Area Map',
      description: seed.access,
      url: seed.officialUrl,
      lat: seed.lat,
      lng: seed.lng,
      image_url: seed.image,
      image_credit: 'Wikimedia Commons',
    },
    {
      title: 'Timing Check',
      description: seed.season,
      url: seed.officialUrl,
    },
  ];
  const story = `${seed.title} is a waterfall stop in ${seed.region}. ${seed.summary} Check current access, weather, closures, and local rules before building a day around it.`;
  return {
    id,
    category: 'Waterfall',
    subcategories: ['waterfalls', 'viewpoints', 'trails'],
    quality: 'official_plus_open_media',
    quality_score: 86,
    search_aliases: ['waterfall', 'waterfalls', 'falls', 'cascade', seed.region],
    best_season: seed.season,
    access: { summary: seed.access },
    safety: { summary: seed.safety },
    sources: [
      { title: `${seed.title} access`, publisher: 'Official source', url: seed.officialUrl, kind: 'official' },
      { title: `${seed.title} image reference`, publisher: 'Wikimedia Commons', url: seed.wikiUrl, kind: 'open_media' },
    ],
    card: {
      title: seed.title,
      region: seed.region,
      headline: seed.highlight,
      summary: seed.summary,
      highlight: seed.highlight,
      facts: [seed.height, seed.access, seed.season, seed.safety],
    },
    summary: {
      id,
      title: seed.title,
      category: 'Waterfall',
      explore_group: 'water',
      state: seed.state,
      region: seed.region,
      lat: seed.lat,
      lng: seed.lng,
      rank: 420 + index,
      hero_rank: 28 + index,
      tags: ['waterfalls', 'falls', 'viewpoint', 'trail', 'scenic'],
      badges: ['Waterfall'],
      hook: seed.highlight,
      short_description: seed.summary,
      thumbnail_url: seed.image,
      image_url: seed.image,
      image_credit: 'Wikimedia Commons',
      image_license: 'Open image reference',
      source_url: seed.officialUrl,
      source_title: 'Official access source',
    },
    profile: {
      hook: seed.highlight,
      summary: seed.summary,
      story,
      why_it_matters: seed.highlight,
      what_to_know: `${seed.access}. ${seed.safety}.`,
      best_time_to_stop: seed.season,
      access_notes: seed.access,
      nearby_context: 'Use the area map to layer trailheads, campgrounds, parking, fuel, weather, and road access around this waterfall.',
    },
    audio_script: story,
    wiki_extract: '',
    source_pack: {
      quality: 'official',
      primary: 'Official access source',
      official_url: seed.officialUrl,
      sources: [
        { title: `${seed.title} access`, publisher: 'Official source', url: seed.officialUrl, kind: 'official' },
        { title: `${seed.title} open image`, publisher: 'Wikimedia Commons', url: seed.wikiUrl, kind: 'open_media' },
      ],
      photos: [{ url: seed.image, caption: seed.title, credit: 'Wikimedia Commons' }],
      activities: ['Waterfall', 'Viewpoint', 'Trail access', 'Photography'],
      things_to_do: thingsToDo,
      things_to_see: [
        {
          title: seed.title,
          description: seed.summary,
          url: seed.officialUrl,
          lat: seed.lat,
          lng: seed.lng,
          image_url: seed.image,
          image_credit: 'Wikimedia Commons',
        },
      ],
      source_note: 'Curated with official access pages and open image references. Verify current access, fees, permits, closures, and rules before you go.',
      license: 'Open image reference; verify media license at source.',
      image_asset: seed.image,
    },
    facts: {
      coordinates: `${seed.lat.toFixed(5)}, ${seed.lng.toFixed(5)}`,
      source_url: seed.officialUrl,
      source_title: 'Official access source',
      official_url: seed.officialUrl,
      source_quality: 'official',
      last_updated: LAST_UPDATED,
    },
    attribution: 'Official access source + Wikimedia Commons image reference',
  };
}

function buildYosemiteParkHub(): ExplorePlaceProfile {
  const id = 'place:nps:yose';
  const story = 'Yosemite National Park works best as a hub: choose the valley, high-country roads, sequoia groves, waterfall walks, longer hikes, campgrounds, or lodge stays before committing the day.';
  return {
    id,
    canonical_role: 'hub',
    category: 'Parks',
    subcategories: ['parks', 'trails', 'waterfalls', 'camp', 'huts', 'views'],
    quality: 'official_plus_open_media',
    quality_score: 96,
    search_aliases: [
      'yosemite',
      'yosemite national park',
      'things to do in yosemite',
      'yosemite things to do',
      'yosemite camping',
      'yosemite lodging',
      'yosemite trails',
      'yosemite waterfalls',
    ],
    best_season: 'Year-round, with seasonal road and trail checks',
    access: { summary: 'Yosemite Valley, Wawona, Tioga Road, Glacier Point Road, and gateway towns' },
    safety: { summary: 'Reservations, road openings, water, heat, snow, smoke, river conditions, and permits can shape the plan' },
    sources: [
      { title: 'Yosemite National Park', publisher: 'National Park Service', url: YOSEMITE_PARK_URL, kind: 'official' },
      { title: 'Things to do', publisher: 'National Park Service', url: YOSEMITE_THINGS_TO_DO_URL, kind: 'official' },
      { title: 'Yosemite hiking', publisher: 'National Park Service', url: YOSEMITE_TRAILS_URL, kind: 'official' },
    ],
    card: {
      title: 'Yosemite National Park',
      region: 'Sierra Nevada',
      headline: 'Waterfalls, granite walls, valley trails, sequoias, campgrounds, and lodge stays.',
      summary: 'Use Yosemite as the main hub for trails, waterfalls, viewpoints, camping, lodging, visitor centers, and current access checks.',
      highlight: 'Start here, then drill into Yosemite trails, Yosemite Falls, campgrounds, lodging, and visitor services.',
      facts: ['National Park Service', 'Trails', 'Waterfalls', 'Campgrounds', 'Lodging'],
    },
    summary: {
      id,
      title: 'Yosemite National Park',
      category: 'Parks',
      explore_group: 'parks',
      state: 'CA',
      region: 'Sierra Nevada',
      lat: 37.7485,
      lng: -119.5870,
      rank: 4,
      hero_rank: 4,
      tags: ['parks', 'trails', 'waterfalls', 'camping', 'lodging', 'views', 'yosemite'],
      badges: ['Parks', 'Official'],
      hook: 'Yosemite hub for trails, waterfalls, viewpoints, campgrounds, lodging, and current access checks.',
      short_description: 'Plan Yosemite from one hub: trails, falls, viewpoints, campgrounds, lodging, visitor centers, and road status.',
      thumbnail_url: GLACIER_POINT_IMAGE,
      image_url: GLACIER_POINT_IMAGE,
      image_credit: 'Wikimedia Commons',
      image_license: 'Open image reference',
      source_url: YOSEMITE_PARK_URL,
      source_title: 'National Park Service',
    },
    profile: {
      hook: 'Plan Yosemite from one place, then drill into the day you actually want.',
      summary: 'Yosemite combines short valley walks, high-exposure trails, major waterfalls, sequoia groves, campgrounds, lodging, shuttles, permits, and seasonal roads.',
      story,
      why_it_matters: 'Yosemite choices are tightly linked: a campground, valley shuttle, trailhead, road opening, or permit can decide the entire day.',
      what_to_know: 'Check reservations, road openings, trail closures, water, smoke, snow, heat, river conditions, and permit requirements before building the day.',
      best_time_to_stop: 'Year-round, with spring waterfalls, summer high country, fall shoulder-season access, and winter road limits.',
      access_notes: 'Use the official park pages for entrance reservations, campground rules, lodging windows, shuttle details, road status, and closures.',
      nearby_context: 'Yosemite Valley trails, waterfalls, campgrounds, visitor centers, lodging, fuel towns, and gateway roads sit close together but can require different timing.',
    },
    audio_script: story,
    wiki_extract: '',
    source_pack: {
      quality: 'official',
      primary: 'National Park Service',
      official_url: YOSEMITE_PARK_URL,
      nps_park_code: 'yose',
      sources: [
        { title: 'Yosemite National Park', publisher: 'National Park Service', url: YOSEMITE_PARK_URL, kind: 'official' },
        { title: 'Things to do', publisher: 'National Park Service', url: YOSEMITE_THINGS_TO_DO_URL, kind: 'official' },
        { title: 'Hiking', publisher: 'National Park Service', url: YOSEMITE_TRAILS_URL, kind: 'official' },
        { title: 'Camping', publisher: 'National Park Service', url: YOSEMITE_CAMPING_URL, kind: 'official' },
        { title: 'Lodging', publisher: 'National Park Service', url: YOSEMITE_LODGING_URL, kind: 'official' },
      ],
      photos: [
        { url: GLACIER_POINT_IMAGE, caption: 'Glacier Point', credit: 'Wikimedia Commons' },
        { url: YOSEMITE_FALLS_IMAGE, caption: 'Yosemite Falls', credit: 'Wikimedia Commons' },
        { url: MARIPOSA_GROVE_IMAGE, caption: 'Mariposa Grove', credit: 'Wikimedia Commons' },
      ],
      activities: ['Hiking', 'Waterfalls', 'Viewpoints', 'Camping', 'Lodging', 'Visitor centers'],
      things_to_do: [
        { title: 'Yosemite Trails', description: 'Compare Mist Trail, Half Dome, Mirror Lake, Yosemite Falls, Taft Point, and Mariposa Grove.', url: YOSEMITE_TRAILS_URL, lat: 37.7485, lng: -119.5870, image_url: GLACIER_POINT_IMAGE, source_label: 'National Park Service', category: 'Trails' },
        { title: 'Mist Trail', description: 'Waterfall route toward Vernal Fall with wet steps and heavy peak-season use.', url: 'https://www.nps.gov/yose/planyourvisit/vernalnevadatrail.htm', lat: 37.7325, lng: -119.5586, image_url: VERNAL_FALL_IMAGE, source_label: 'National Park Service', category: 'Trail' },
        { title: 'Half Dome', description: 'Permit-only cable route with exposure, elevation, and all-day commitment.', url: 'https://www.nps.gov/yose/planyourvisit/halfdome.htm', lat: 37.7460, lng: -119.5332, image_url: HALF_DOME_IMAGE, source_label: 'National Park Service', category: 'Permit trail' },
        { title: 'Mariposa Grove', description: 'Giant sequoia grove walks near the South Entrance with seasonal shuttle and snow checks.', url: YOSEMITE_THINGS_TO_DO_URL, lat: 37.5116, lng: -119.6008, image_url: MARIPOSA_GROVE_IMAGE, source_label: 'National Park Service', category: 'Sequoia grove' },
      ],
      things_to_see: [
        { title: 'Yosemite Falls', description: 'Major valley waterfall with lower-view access and a strenuous upper-falls trail.', url: 'https://www.nps.gov/yose/planyourvisit/yosemitefalls.htm', lat: 37.756845, lng: -119.596785, image_url: YOSEMITE_FALLS_IMAGE, source_label: 'National Park Service', category: 'Waterfall' },
        { title: 'Glacier Point', description: 'High viewpoint over Yosemite Valley, Half Dome, and the high country when the road is open.', url: YOSEMITE_THINGS_TO_DO_URL, lat: 37.7309, lng: -119.5731, image_url: GLACIER_POINT_IMAGE, source_label: 'National Park Service', category: 'Viewpoint' },
        { title: 'Mirror Lake', description: 'Seasonal valley lake and easy walk below Half Dome.', url: 'https://www.nps.gov/yose/planyourvisit/mirrorlaketrail.htm', lat: 37.7485, lng: -119.5491, image_url: MIRROR_LAKE_IMAGE, source_label: 'National Park Service', category: 'Lake walk' },
      ],
      campgrounds: [
        { title: 'Yosemite campgrounds', description: 'Use the official camping page for reservation windows, seasonal openings, and campground rules.', url: YOSEMITE_CAMPING_URL, source_label: 'National Park Service', category: 'Camping' },
        { title: 'Yosemite lodging', description: 'Use the official lodging page for in-park hotels, cabins, tent cabins, and seasonal availability.', url: YOSEMITE_LODGING_URL, source_label: 'National Park Service', category: 'Lodging' },
      ],
      visitor_centers: [
        { title: 'Yosemite Valley Visitor Center', description: 'Main visitor services in Yosemite Valley.', url: YOSEMITE_VISITOR_URL, lat: 37.7487, lng: -119.5871, source_label: 'National Park Service', category: 'Visitor center' },
      ],
      source_note: 'Curated with National Park Service pages and open image references. Verify current reservations, road status, closures, permits, and seasonal services before you go.',
      license: 'Open image reference; verify media license at source.',
      image_asset: GLACIER_POINT_IMAGE,
    },
    facts: {
      coordinates: '37.74850, -119.58700',
      source_url: YOSEMITE_PARK_URL,
      source_title: 'National Park Service',
      official_url: YOSEMITE_PARK_URL,
      source_quality: 'official',
      last_updated: LAST_UPDATED,
    },
    attribution: 'National Park Service pages + Wikimedia Commons image references',
  };
}

function buildYosemiteTrailArea(): ExplorePlaceProfile {
  const id = 'explore:trails:yosemite-trails';
  const story = 'Yosemite Trails brings the valley classics into one place: waterfall walks, Half Dome permits, family loops, cliff viewpoints, and giant sequoia routes. Pick the trail by distance, route type, elevation, and current access.';
  return {
    id,
    category: 'Trails',
    subcategories: ['trails', 'hiking'],
    quality: 'official_plus_open_media',
    quality_score: 92,
    search_aliases: ['yosemite trails', 'yosemite hikes', 'mist trail', 'half dome', 'mirror lake', 'upper yosemite fall'],
    best_season: 'Year-round, check road and trail status',
    access: { summary: 'Yosemite Valley, Glacier Point Road, and South Entrance trailheads' },
    safety: { summary: 'Permits, snow, heat, wet rock, and cliff exposure vary by trail' },
    trails: YOSEMITE_TRAILS,
    sources: [
      { title: 'Yosemite hiking', publisher: 'National Park Service', url: YOSEMITE_TRAILS_URL, kind: 'official' },
      { title: 'Open Yosemite trail imagery', publisher: 'Wikimedia Commons', url: 'https://commons.wikimedia.org/wiki/Category:Yosemite_National_Park', kind: 'open_media' },
    ],
    card: {
      title: 'Yosemite Trails',
      region: 'Yosemite National Park',
      headline: 'Valley walks, waterfall climbs, big-view routes, and permit hikes in one trail list.',
      summary: 'Choose Yosemite hikes by distance, route type, elevation, time, and current access.',
      highlight: 'Open the area to compare Mist Trail, Half Dome, Mirror Lake, Yosemite Falls, Taft Point, and sequoia routes.',
      facts: ['6 trails', 'Easy - Hard', 'Year-round status checks', 'Official trail pages'],
    },
    summary: {
      id,
      title: 'Yosemite Trails',
      category: 'Trails',
      explore_group: 'trails',
      state: 'CA',
      region: 'Yosemite National Park',
      lat: 37.7485,
      lng: -119.5870,
      rank: 12,
      hero_rank: 12,
      tags: ['trails', 'hiking', 'waterfalls', 'views', 'loops', 'yosemite'],
      badges: ['Trails'],
      hook: 'Yosemite hikes with distance, route type, elevation, and trail-specific details.',
      short_description: 'Choose Yosemite hikes by distance, route type, elevation, time, and current access.',
      thumbnail_url: GLACIER_POINT_IMAGE,
      image_url: GLACIER_POINT_IMAGE,
      image_credit: 'Wikimedia Commons',
      image_license: 'Open image reference',
      source_url: YOSEMITE_TRAILS_URL,
      source_title: 'National Park Service hiking page',
    },
    profile: {
      hook: 'Explore trails in and around Yosemite National Park.',
      summary: 'From easy valley walks to exposed all-day routes, Yosemite trails need distance, route type, elevation, access, and weather checks.',
      story,
      why_it_matters: 'Yosemite has very different trail days in the same area: short loops, wet waterfall steps, permit routes, and high-exposure viewpoints.',
      what_to_know: 'Check current trail status, seasonal road access, permits, weather, daylight, and water before starting.',
      best_time_to_stop: 'Year-round, check road and trail status',
      access_notes: 'Use Yosemite Valley shuttles and signed trailheads where available. Glacier Point Road and Mariposa Grove access can be seasonal.',
      nearby_context: 'Trailheads, campgrounds, waterfall stops, fuel towns, and weather checks sit close together in Yosemite.',
    },
    audio_script: story,
    wiki_extract: '',
    source_pack: {
      quality: 'official',
      primary: 'National Park Service',
      official_url: YOSEMITE_TRAILS_URL,
      nps_park_code: 'yose',
      sources: [
        { title: 'Yosemite hiking', publisher: 'National Park Service', url: YOSEMITE_TRAILS_URL, kind: 'official' },
        { title: 'Open Yosemite images', publisher: 'Wikimedia Commons', url: 'https://commons.wikimedia.org/wiki/Category:Yosemite_National_Park', kind: 'open_media' },
      ],
      photos: YOSEMITE_TRAILS.slice(0, 4).map(trail => ({ url: trail.image_url, caption: trail.title, credit: 'Wikimedia Commons' })),
      activities: ['Hiking', 'Waterfalls', 'Viewpoints', 'Backcountry access'],
      things_to_do: YOSEMITE_TRAILS.map(trail => ({
        kind: 'trail',
        source: 'National Park Service',
        source_id: trail.id,
        title: trail.title,
        description: trailSourcePackDescription(trail),
        url: trail.source_url || YOSEMITE_TRAILS_URL,
        lat: trail.lat,
        lng: trail.lng,
        image_url: trail.image_url,
        image_credit: 'Wikimedia Commons',
        source_label: 'National Park Service',
        category: `${trail.difficulty} ${trail.route_type}`,
        amenities: trail.highlights,
        distance_mi: trail.distance_mi,
      })),
      things_to_see: [
        { title: 'Vernal Fall', description: 'Mist Trail waterfall viewpoint.', url: 'https://www.nps.gov/yose/planyourvisit/vernalnevadatrail.htm', image_url: VERNAL_FALL_IMAGE },
        { title: 'Half Dome', description: 'Permit-only cable route and Yosemite landmark.', url: 'https://www.nps.gov/yose/planyourvisit/halfdome.htm', image_url: HALF_DOME_IMAGE },
        { title: 'Mirror Lake', description: 'Seasonal lake and easy valley walk.', url: 'https://www.nps.gov/yose/planyourvisit/mirrorlaketrail.htm', image_url: MIRROR_LAKE_IMAGE },
      ],
      source_note: 'Trail details use official Yosemite hiking pages and open image references. Check current trail status before starting.',
      license: 'Open image reference; verify media license at source.',
      image_asset: GLACIER_POINT_IMAGE,
    },
    facts: {
      coordinates: '37.74850, -119.58700',
      source_url: YOSEMITE_TRAILS_URL,
      source_title: 'National Park Service hiking page',
      official_url: YOSEMITE_TRAILS_URL,
      source_quality: 'official',
      last_updated: LAST_UPDATED,
    },
    attribution: 'National Park Service trail pages + Wikimedia Commons image references',
  };
}

function normalizeTitle(value: string) {
  return value
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}
