apply plugin: 'com.android.library'

group = 'expo.modules.missionanimator'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useDefaultAndroidSdkVersions()

android {
  namespace "expo.modules.missionanimator"
}

dependencies {
  def mapboxVersion = rootProject.ext.has('RNMapboxMapsVersion') ? rootProject.ext.RNMapboxMapsVersion : '11.16.0'
  implementation "com.mapbox.maps:android:${mapboxVersion}"
}
