from __future__ import annotations

import copy
import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import urlsplit

try:
    from scripts.explore_sources.nps.import_nps import safe_reader_text
except ModuleNotFoundError:  # Direct execution through scripts/*.py.
    from explore_sources.nps.import_nps import safe_reader_text


NPS_MEDIA_POLICY_URL = "https://www.nps.gov/aboutus/disclaimer.htm"
NPS_MEDIA_RIGHTS_STATUS = "nps_created_public_domain_presumption"
NPS_MEDIA_RIGHTS_STATE = "source_terms_reviewed"
NPS_MEDIA_DISTRIBUTION_STATUS = "approved"
NPS_AGGREGATE_CACHE_NAME = (
    "source-pack_with-places-thingstodo-campgrounds-visitorcenters-"
    "alerts-articles_max-500.json"
)
NPS_MEDIA_COLLECTION_KEYS = frozenset({"media", "photos", "images"})
GENERATED_CARD_WARNINGS = frozenset({
    "check official source or local rules",
    "verify access",
})
APPROVED_CREDIT_RE = re.compile(
    r"^(?:NPS(?:\s+Photo)?|National Park Service)(?:\b|[\s/:;,-])",
    re.IGNORECASE,
)
DISALLOWED_RIGHTS_RE = re.compile(
    r"(?:\bcopyright(?:ed)?\b|\bcourtesy\b|\bpermission\b|"
    r"\ball rights reserved\b|\brestricted\b|\bartificial intelligence\b|\bAI\b|"
    r"\bgenerated by\b)",
    re.IGNORECASE,
)
RIGHTS_SIGNAL_KEYS = frozenset({
    "ai_generated",
    "ai_modified",
    "copyright",
    "credit",
    "distribution",
    "generated_by_ai",
    "generation_method",
    "is_ai",
    "is_synthetic",
    "license",
    "modified_by_ai",
    "modification_method",
    "permission",
    "restricted",
    "rights",
})


class NpsMediaEvidenceError(ValueError):
    """Raised when the selected cached NPS evidence cannot be resolved exactly."""


@dataclass(frozen=True)
class NpsMediaTrace:
    url: str
    exact_credit: str
    source_page_url: str
    cache_path: str
    cache_sha256: str
    json_pointer: str
    fetched_at: int
    approved: bool
    decision_reason: str
    raw_media: dict[str, Any]


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _json_pointer_part(value: str | int) -> str:
    return str(value).replace("~", "~0").replace("/", "~1")


def _is_https_nps_url(value: Any) -> bool:
    parsed = urlsplit(str(value or "").strip())
    host = (parsed.hostname or "").strip().rstrip(".").casefold()
    return (
        parsed.scheme.casefold() == "https"
        and bool(parsed.path)
        and (host == "nps.gov" or host.endswith(".nps.gov"))
    )


def _source_page(value: Any) -> str:
    url = str(value or "").strip()
    try:
        parsed = urlsplit(url)
        host = (parsed.hostname or "").strip().rstrip(".").casefold()
        port = parsed.port
    except ValueError:
        return ""
    if (
        parsed.scheme.casefold() == "http"
        and bool(parsed.path)
        and not parsed.username
        and not parsed.password
        and port in (None, 80)
        and (host == "nps.gov" or host.endswith(".nps.gov"))
    ):
        # Older NPS API records still carry canonical page links as HTTP.
        # Preserve the exact host/path/query while normalizing transport so
        # exact-page media evidence can match the reader's HTTPS-only URL.
        url = parsed._replace(scheme="https", netloc=str(parsed.hostname or host)).geturl()
    if not _is_https_nps_url(url):
        return ""
    parsed = urlsplit(url)
    if "/common/uploads/" in parsed.path.casefold():
        return ""
    return url


def _rights_signal_text(value: Any, key: str = "") -> Iterable[str]:
    if isinstance(value, dict):
        for child_key, child in value.items():
            normalized = str(child_key).strip().casefold()
            if normalized in RIGHTS_SIGNAL_KEYS or any(
                token in normalized
                for token in ("credit", "copyright", "license", "permission", "rights", "restricted", "ai_")
            ):
                yield from _rights_signal_text(child, normalized)
    elif isinstance(value, list):
        for child in value:
            yield from _rights_signal_text(child, key)
    elif value not in (None, "", False, 0):
        yield str(value)


def _explicit_ai_flag(value: Any) -> bool:
    if not isinstance(value, dict):
        return False
    for key in (
        "ai_generated",
        "ai_modified",
        "generated_by_ai",
        "is_ai",
        "is_synthetic",
        "modified_by_ai",
    ):
        flag = value.get(key)
        if flag is True or str(flag or "").strip().casefold() in {
            "1",
            "ai",
            "generated",
            "modified",
            "true",
            "yes",
        }:
            return True
    return False


def _media_decision(media: dict[str, Any], source_page_url: str) -> tuple[bool, str]:
    url = str(media.get("url") or "").strip()
    credit = str(media.get("credit") or "").strip()
    if not _is_https_nps_url(url):
        return False, "image_url_is_not_https_nps"
    if not source_page_url:
        return False, "containing_nps_page_is_missing"
    if not credit:
        return False, "exact_credit_is_missing"
    if not APPROVED_CREDIT_RE.match(credit):
        return False, "exact_credit_is_not_nps_prefixed"
    if _explicit_ai_flag(media):
        return False, "explicit_ai_media_is_excluded"
    signals = " | ".join(_rights_signal_text(media))
    if DISALLOWED_RIGHTS_RE.search(signals):
        return False, "rights_signal_requires_individual_clearance"
    return True, "cached_official_nps_object_with_nps_prefixed_credit"


def _cache_display_path(path: Path, evidence_root: Path) -> str:
    try:
        return path.relative_to(evidence_root).as_posix()
    except ValueError:
        return path.as_posix()


def _trace_cache_images(
    value: Any,
    *,
    pointer: str,
    inherited_page: str,
    fallback_page: str,
    cache_path: str,
    cache_sha256: str,
    fetched_at: int,
) -> list[NpsMediaTrace]:
    traces: list[NpsMediaTrace] = []
    if isinstance(value, dict):
        current_page = _source_page(value.get("url")) or inherited_page or fallback_page
        for key, child in value.items():
            child_pointer = f"{pointer}/{_json_pointer_part(key)}"
            if key == "images" and isinstance(child, list):
                for index, media in enumerate(child):
                    if not isinstance(media, dict):
                        continue
                    source_page_url = current_page or fallback_page
                    approved, reason = _media_decision(media, source_page_url)
                    traces.append(NpsMediaTrace(
                        url=str(media.get("url") or "").strip(),
                        exact_credit=str(media.get("credit") or "").strip(),
                        source_page_url=source_page_url,
                        cache_path=cache_path,
                        cache_sha256=cache_sha256,
                        json_pointer=f"{child_pointer}/{index}",
                        fetched_at=fetched_at,
                        approved=approved,
                        decision_reason=reason,
                        raw_media=copy.deepcopy(media),
                    ))
                continue
            traces.extend(_trace_cache_images(
                child,
                pointer=child_pointer,
                inherited_page=current_page,
                fallback_page=fallback_page,
                cache_path=cache_path,
                cache_sha256=cache_sha256,
                fetched_at=fetched_at,
            ))
    elif isinstance(value, list):
        for index, child in enumerate(value):
            traces.extend(_trace_cache_images(
                child,
                pointer=f"{pointer}/{index}",
                inherited_page=inherited_page,
                fallback_page=fallback_page,
                cache_path=cache_path,
                cache_sha256=cache_sha256,
                fetched_at=fetched_at,
            ))
    return traces


def _cache_file_for_code(cache_dir: Path, park_code: str) -> Path:
    matches = sorted(cache_dir.glob(f"source-pack_codes-{park_code}_with-*.json"))
    if len(matches) != 1:
        raise NpsMediaEvidenceError(
            f"Expected one immutable NPS source-pack cache for {park_code}; found {len(matches)}"
        )
    return matches[0]


def _cache_traces_for_code(
    payload: dict[str, Any],
    park_code: str,
    *,
    path: Path,
    evidence_root: Path,
) -> list[NpsMediaTrace]:
    parks = payload.get("data") or payload.get("parks") or []
    matching_parks = [
        (index, park)
        for index, park in enumerate(parks)
        if isinstance(park, dict)
        and str(park.get("parkCode") or park.get("id") or "").strip().casefold() == park_code
    ]
    if not matching_parks:
        return []
    display_path = _cache_display_path(path, evidence_root)
    cache_hash = _sha256(path)
    fetched_at = int(payload.get("fetched_at") or 0)
    traces: list[NpsMediaTrace] = []
    fallback_page = _source_page(matching_parks[0][1].get("url"))
    for index, park in matching_parks:
        traces.extend(_trace_cache_images(
            park,
            pointer=f"/data/{index}",
            inherited_page=fallback_page,
            fallback_page=fallback_page,
            cache_path=display_path,
            cache_sha256=cache_hash,
            fetched_at=fetched_at,
        ))
    related = payload.get("related") if isinstance(payload.get("related"), dict) else {}
    related_value = related.get(park_code)
    if related_value is None:
        related_value = next(
            (value for key, value in related.items() if str(key).strip().casefold() == park_code),
            None,
        )
    if related_value is not None:
        traces.extend(_trace_cache_images(
            related_value,
            pointer=f"/related/{_json_pointer_part(park_code)}",
            inherited_page=fallback_page,
            fallback_page=fallback_page,
            cache_path=display_path,
            cache_sha256=cache_hash,
            fetched_at=fetched_at,
        ))
    return traces


def load_nps_media_traces(
    cache_dir: str | Path,
    park_codes: Iterable[str],
    *,
    evidence_root: str | Path,
    aggregate_cache_path: str | Path | None = None,
) -> dict[str, dict[str, list[NpsMediaTrace]]]:
    cache_root = Path(cache_dir).resolve()
    root = Path(evidence_root).resolve()
    aggregate_path = Path(aggregate_cache_path).resolve() if aggregate_cache_path else cache_root / NPS_AGGREGATE_CACHE_NAME
    aggregate_payload: dict[str, Any] | None = None
    if aggregate_path.is_file():
        loaded = json.loads(aggregate_path.read_text())
        if not isinstance(loaded, dict):
            raise NpsMediaEvidenceError(f"NPS aggregate cache is not an object: {aggregate_path}")
        aggregate_payload = loaded
    indexes: dict[str, dict[str, list[NpsMediaTrace]]] = {}
    for raw_code in park_codes:
        park_code = str(raw_code).strip().casefold()
        path = _cache_file_for_code(cache_root, park_code)
        payload = json.loads(path.read_text())
        if not isinstance(payload, dict):
            raise NpsMediaEvidenceError(f"NPS cache is not an object: {path}")
        traces = _cache_traces_for_code(payload, park_code, path=path, evidence_root=root)
        by_url: dict[str, list[NpsMediaTrace]] = {}
        for trace in traces:
            if trace.url:
                by_url.setdefault(trace.url, []).append(trace)
        if aggregate_payload is not None:
            fallback_traces = _cache_traces_for_code(
                aggregate_payload,
                park_code,
                path=aggregate_path,
                evidence_root=root,
            )
            for trace in fallback_traces:
                # The aggregate is exact secondary evidence only. It may not
                # replace or weaken a decision made from the code-specific cache.
                if trace.url and trace.url not in by_url:
                    by_url.setdefault(trace.url, []).append(trace)
        indexes[park_code] = by_url
    return indexes


def _approved_trace(
    traces_by_url: dict[str, list[NpsMediaTrace]],
    url: str,
    *,
    desired_page: str = "",
) -> NpsMediaTrace | None:
    traces = traces_by_url.get(url, [])
    if not traces:
        return None
    desired = _source_page(desired_page)
    if desired:
        # Media URLs are sometimes reused across NPS pages. A request scoped to
        # one page must be supported by that page's own cached evidence; an
        # approval from a different page cannot fill an absent or rejected
        # exact-page trace.
        traces = [trace for trace in traces if trace.source_page_url == desired]
        if not traces:
            return None
    distinct_credits = {trace.exact_credit.casefold() for trace in traces if trace.exact_credit}
    if len(distinct_credits) != 1:
        return None
    approved = [trace for trace in traces if trace.approved]
    if not approved:
        return None
    return sorted(
        approved,
        key=lambda trace: (trace.source_page_url, trace.json_pointer, trace.cache_path),
    )[0]


def _evidence(trace: NpsMediaTrace) -> dict[str, Any]:
    return {
        "source_cache_path": trace.cache_path,
        "source_cache_sha256": trace.cache_sha256,
        "json_pointer": trace.json_pointer,
        "fetched_at": trace.fetched_at,
        "policy_url": NPS_MEDIA_POLICY_URL,
        "decision_reason": trace.decision_reason,
    }


def _approved_media_record(media: dict[str, Any], trace: NpsMediaTrace) -> dict[str, Any]:
    approved = copy.deepcopy(media)
    approved["credit"] = trace.exact_credit
    approved["distribution_status"] = NPS_MEDIA_DISTRIBUTION_STATUS
    approved["rights_status"] = NPS_MEDIA_RIGHTS_STATUS
    approved["rights_state"] = NPS_MEDIA_RIGHTS_STATE
    approved["source_page_url"] = trace.source_page_url
    approved["rights_evidence"] = _evidence(trace)
    return approved


def _normalize_media_collection(
    items: list[Any],
    traces_by_url: dict[str, list[NpsMediaTrace]],
    *,
    desired_page: str,
) -> list[Any]:
    out: list[Any] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        url = str(item.get("url") or "").strip()
        trace = _approved_trace(traces_by_url, url, desired_page=desired_page)
        if trace is None or _explicit_ai_flag(item):
            continue
        signals = " | ".join(_rights_signal_text(item))
        if DISALLOWED_RIGHTS_RE.search(signals):
            continue
        out.append(_approved_media_record(item, trace))
    return out


def _strip_child_image_fields(value: dict[str, Any]) -> None:
    for key in tuple(value):
        if str(key).startswith("image_"):
            value.pop(key, None)


def _normalize_media_tree(
    value: Any,
    traces_by_url: dict[str, list[NpsMediaTrace]],
    *,
    inherited_page: str,
) -> Any:
    if isinstance(value, dict):
        current_page = _source_page(value.get("url")) or inherited_page
        for key in tuple(value):
            child = value[key]
            if str(key).casefold() in NPS_MEDIA_COLLECTION_KEYS and isinstance(child, list):
                value[key] = _normalize_media_collection(
                    child,
                    traces_by_url,
                    desired_page=current_page,
                )
            else:
                value[key] = _normalize_media_tree(
                    child,
                    traces_by_url,
                    inherited_page=current_page,
                )
        image_url = str(value.get("image_url") or "").strip()
        if image_url:
            trace = _approved_trace(traces_by_url, image_url, desired_page=current_page)
            if trace is None or _explicit_ai_flag(value):
                _strip_child_image_fields(value)
            else:
                signals = " | ".join(_rights_signal_text(value))
                if DISALLOWED_RIGHTS_RE.search(signals):
                    _strip_child_image_fields(value)
                else:
                    value["image_credit"] = trace.exact_credit
                    value["image_distribution_status"] = NPS_MEDIA_DISTRIBUTION_STATUS
                    value["image_rights_status"] = NPS_MEDIA_RIGHTS_STATUS
                    value["image_rights_state"] = NPS_MEDIA_RIGHTS_STATE
                    value["image_source_page_url"] = trace.source_page_url
                    value["image_rights_evidence"] = _evidence(trace)
        return value
    if isinstance(value, list):
        return [
            _normalize_media_tree(item, traces_by_url, inherited_page=inherited_page)
            for item in value
        ]
    return value


def _sanitize_reader_tree(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _sanitize_reader_tree(child) for key, child in value.items()}
    if isinstance(value, list):
        return [_sanitize_reader_tree(child) for child in value]
    if isinstance(value, str):
        return safe_reader_text(value)
    return value


def _remove_generated_card_warnings(place: dict[str, Any]) -> None:
    card = place.get("card")
    if not isinstance(card, dict) or not isinstance(card.get("warnings"), list):
        return
    warnings = [
        warning
        for warning in card["warnings"]
        if str(warning or "").strip().casefold() not in GENERATED_CARD_WARNINGS
    ]
    if warnings:
        card["warnings"] = warnings
    else:
        card.pop("warnings", None)


def normalize_selected_nps_places(
    places: list[dict[str, Any]],
    *,
    cache_dir: str | Path,
    evidence_root: str | Path,
) -> list[dict[str, Any]]:
    """Return a cache-evidenced NPS media view without mutating source artifacts."""
    def is_nps_place(place: dict[str, Any]) -> bool:
        place_id = str(place.get("id") or "")
        return place_id.startswith("place:nps:") or place_id.startswith("place:nps-child:")

    park_codes = sorted({
        str((place.get("source_pack") or {}).get("nps_park_code") or "").strip().casefold()
        for place in places
        if isinstance(place, dict) and is_nps_place(place)
    } - {""})
    indexes = load_nps_media_traces(cache_dir, park_codes, evidence_root=evidence_root)
    normalized: list[dict[str, Any]] = []
    for original in places:
        place = copy.deepcopy(original)
        if not is_nps_place(place):
            normalized.append(place)
            continue
        code = str((place.get("source_pack") or {}).get("nps_park_code") or "").strip().casefold()
        if not code or code not in indexes:
            raise NpsMediaEvidenceError(f"Selected NPS place lacks cache evidence: {place.get('id')}")
        place = _sanitize_reader_tree(place)
        _remove_generated_card_warnings(place)
        official_page = _source_page((place.get("source_pack") or {}).get("official_url"))
        place = _normalize_media_tree(place, indexes[code], inherited_page=official_page)
        normalized.append(place)
    return normalized
